### ISSUE TITLE
Add support for NUCLEO-L4R5ZI

### ISSUE THREAD

**Issue by lufri** [platformio/platform-ststm32#100]
[NUCLEO-144 STM32L4 with STM32L4R5ZIT6](http://www.st.com/content/st_com/en/products/evaluation-tools/product-evaluation-tools/mcu-eval-tools/stm32-mcu-eval-tools/stm32-mcu-nucleo/nucleo-l4r5zi.html)

**Comment by ivankravets** [comment]
Resolved via https://github.com/platformio/platform-ststm32/commit/cf959b5a84f62386b1e86636f36eb979ed15d8d4
