### ISSUE TITLE
Adding syscalls.c to project

### ISSUE THREAD

**Issue by benariamir** [platformio/platform-ststm32#104]
Hey everyone,
I'm porting an embedded application project, written by an external freelancer, to Platform.io .
(I should mention I'm a newbie to embedded development)

I've managed to port most of the code, but the application freezes or crashes every time a call to printf is being made - whose input is expected to be conducted to the UART.

I made sure that transmitting with HAL_UART_Transmit works as expected. 

The freelancer was following this [comment](https://community.st.com/thread/10610#comment-162597)/post and copied syscalls.c to the project's root folder. I failed to do so with platformio.

How do I or where do I add syscalls.c to my project and compile with it?

I have the following platformio.ini:
[env:nucleo_l476rg]
platform = ststm32
board = nucleo_l476rg
framework = stm32cube
build_flags = -std=gnu99

Thanks.

**Comment by ubis** [comment]
I assume you want to use float in printf. By default, it's disabled. No need to include `syscalls.c` or any other file.
Try with: `build_flags = -std=gnu99 -Wl,-u,_printf_float`

**Comment by ivankravets** [comment]
Please reopen if you still need help
