### ISSUE TITLE
Alignment problem in .ld files w/ possible fix

### ISSUE THREAD

**Issue by jcw** [platformio/platform-ststm32#107]
I'm running into a problem with some generated code. For me, it happens with the `cmsis` framework and not in `libopencm3`, but I suspect that's just a coincidence due to the size of the compiled code.

The error does not show up for a build, only during upload (I'm using `blackmagic`):

```

Loading section .text, size 0x66f lma 0x8000000
Error writing data to flash
Loading section .data, size 0x4 lma 0x800066f
Section .text, range 0x8000000 -- 0x800066f: matched.
Section .data, range 0x800066f -- 0x8000673: MIS-MATCHED!
```

Note the non-word-aligned address of the `.data` section. By adding an alignment line in the `stm32f103x8.ld` file, the mismatch goes away:

```
Loading section .text, size 0x66f lma 0x8000000
Loading section .data, size 0x4 lma 0x8000670
Start address 0x8000588, load size 1651
Transfer rate: 16 KB/sec, 550 bytes/write.
Section .text, range 0x8000000 -- 0x800066f: matched.
Section .data, range 0x8000670 -- 0x8000674: matched.
```

The edit I made for this test was in `.platformio/platforms/ststm32/ldscripts/stm32f103x8.ld`, around line 77, changed from:

```
    __exidx_end = .;

    __etext = .;
```

to 

```
    __exidx_end = .;
    . = ALIGN(4);
    __etext = .;
```

I'm not sure it's the right place, or even the right fix. If it is, this bug may affect other `.ld` files as well.

**Comment by ivankravets** [comment]
Thanks!
