### ISSUE TITLE
Can't upload with stlink

### ISSUE THREAD

**Issue by ajiwo** [platformio/platform-ststm32#116]
On MacOS 
PlatformIO, version 3.5.3
platform-ststm32 version 4.2.1

`Error: couldn't open {.pioenvs/bluepill_f103c8/firmware.elf}`

https://github.com/platformio/platform-ststm32/blob/ba4bcd7d86c8708e3723dcd3a8d90644042858f2/builder/main.py#L212

If that line changed to:
` "program {$SOURCE} %s verify reset; shutdown;" % env.BoardConfig().get( `
It worked.

**Comment by ivankravets** [comment]
Please run `pio update`. It should work now
