### ISSUE TITLE
Set mbed library configuration

### ISSUE THREAD

**Issue by masoudr** [platformio/platform-ststm32#125]
Hi,
I'm trying to use some of mbed libraries. Some of them such as [easy-connect](https://github.com/ARMmbed/easy-connect) has a unique configuration that must be put in the `mbed_app.json` file which seems `pio` doesn't support it. So how can I set the proper configuration in the `pio` structure project?
I found that some of libs has already ported in `pio` like [this one](https://platformio.org/lib/show/3222/easy-connect) but It has its configuration too and Im not sure where should I put the exact configs in there.
Thanks.

**Comment by ivankravets** [comment]
1. Support for `mbed_app.json` is added. See https://docs.platformio.org/en/latest/frameworks/mbed.html#the-configuration-system
2. [easy-connect](https://github.com/ARMmbed/easy-connect) is deprecated. See https://github.com/ARMmbed/easy-connect
