### ISSUE TITLE
How is a Variant supposed to be configured to work with the current builder?

### ISSUE THREAD

**Issue by xC0000005** [platformio/platform-ststm32#127]
I had working variant definitions for the MalyanM200 using stm32duino, which worked with earlier versions of PIO, but now the builder expects build.variant to have the MCU in the name (where it used to specify the variant name), and the custom LD scripts aren't read anymore. How should a variant be laid out so it just works once copied into the variants folder?

For STM32GENERIC, since it's pulling down my own builder, it works, but I'd like my stm32duino variant to work as well.

**Comment by ivankravets** [comment]
Please re-test with the latest upstream version https://docs.platformio.org/en/latest/platforms/ststm32.html#upstream

Does it work now?

**Comment by ivankravets** [comment]
Please reopen if you still need help
