### ISSUE TITLE
please add a new boards STM32F103ZET6

### ISSUE THREAD

**Issue by EmiyaNing** [platformio/platform-ststm32#128]

**Comment by ubis** [comment]
See [genericSTM32F103ZE.json](https://github.com/platformio/platform-ststm32/blob/develop/boards/genericSTM32F103ZE.json).
It's not merged yet, so you will need to use development version of ststm32 platform.

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platform-ststm32/pull/119
