### ISSUE TITLE
Need support for mbed 5.9 on stm32

### ISSUE THREAD

**Issue by iitgrad** [platformio/platform-ststm32#134]

**Comment by j0hns0ny** [comment]
Any suggestions on manual upgrade mbed framework is appreciated.

**Comment by ivankravets** [comment]
We are working on that. Please stay tuned with us on https://twitter.com/PlatformIO_Org

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platform-ststm32/commit/6ab6c85966e038b40222c88d3c868a038cf31604
