### ISSUE TITLE
added platform

### ISSUE THREAD

**Issue by mjhejazi** [platformio/platform-ststm32#135]
Please Add platform :
https://github.com/danieleff/STM32GENERIC

**Comment by xC0000005** [comment]
It's hardly official, but you can set your platform to point to Platform=https://github.com/xC0000005/platform-ststm32#M200Toolchain

and it will automatically install and support a version of that. I had to do it as a framework, so library compatibility is broken, but it works for what I needed.

**Comment by ivankravets** [comment]
There is support for official https://github.com/stm32duino/Arduino_Core_STM32 and https://github.com/rogerclarkmelbourne/Arduino_STM32
