### ISSUE TITLE
upload_port for Unix-based OS should be an absolute path

### ISSUE THREAD

**Issue by sedrubal** [platformio/platform-ststm32#138]
[According to the docs](https://github.com/platformio/platformio-docs/blob/a3f4e765e5d146df43b13719782d213cb2658359/projectconf/section_env_upload.rst#upload_port) the `upload_port` for a Unix-based OS has to be e.g. `/dev/ttyUSB0`. But for `ststm32` and `upload_protocol = serial` it has to be e.g. `ttyUSB0`. Otherwise the `stm32flash` program searches for `/dev//dev/ttyUSB0`. I'm not sure if this is intended. 

See https://github.com/platformio/platformio-docs/issues/25

**Comment by ivankravets** [comment]
What is your `platformio.ini`? See https://github.com/platformio/platform-ststm32/blob/develop/builder/main.py#L153

**Comment by ivankravets** [comment]
Similar https://community.platformio.org/t/bug-report-double-dev-in-stm32-serial-upload/4912
