### ISSUE TITLE
Problem to burn bluepill_f103c8 via UART (arduino)

### ISSUE THREAD

**Issue by justgook** [platformio/platform-ststm32#14]
```
Looking for upload disk...
Auto-detected: /dev/cu.SLAB_USBtoUART
Uploading .pioenvs/stm32f103c8t6/firmware.bin
sh: ~/.platformio/packages/framework-arduinoststm32/tools/macosx/: is a directory
*** [upload] Error 126
```

But then i do same with CLI:
```
~/.platformio/packages/framework-arduinoststm32/tools/macosx/stm32flash:$ ./stm32flash -w ~/Projects/test_ST32/.pioenvs/stm32f103c8t6/firmware.bin -v -g 0x0 /dev/cu.SLAB_USBtoUART
```

and that burns normally

for mbed - for now no success at all..

**Comment by ivankravets** [comment]
Could you run it with `--verbose` option?

**Comment by justgook** [comment]
today later - when be at home

**Comment by zgoda** [comment]
To be precise - "bluepill_f103c8" is mbed platform and the only upload protocol that it supports now is stlink. I guess "stm32f103c8t6" is stm32duino platform.

**Comment by justgook** [comment]
so for now there is no official support of bluepill_f103c8 with arduino (stm32duino):
but i can build project via:
```
[env:stm32f103c8t6]
platform = ststm32
framework = arduino
board = bluepill_f103c8
```
code:
```
#include "Arduino.h"
void setup() {
  pinMode(PC13, OUTPUT);
}

void loop() {
  digitalWrite(PC13, HIGH);
  delay(1000);
  digitalWrite(PC13, LOW);
  delay(1000);
}
```

**Comment by justgook** [comment]
I have that - and im able to build app via platformio, and then burn it via CLI app and usb2UART addapter (by the way that was only way how "Disable the flash write-protection" that was set by default on that MCU) (stm32flash -w ~/Projects/test_ST32/.pioenvs/stm32f103c8t6/firmware.bin -v -g 0x0 /dev/cu.SLAB_USBtoUART)  
![some image](http://www.dhresource.com/0x0s/f2-albu-g4-M01-6B-1B-rBVaEFd1j0mAALWRAAP1ioSoyVc625.jpg/wholesale-stm32f103c8t6-arm-stm32-minimum.jpg)

**Comment by zgoda** [comment]
It is supported in both mbed and stm32duino. Please disregard my comment, I think I messed up stm32duino board name with mbed target name.

**Comment by justgook** [comment]
```
gook@work:~/Projects/arduino_ST32⚡pio run -v --target upload
[Mon Oct 10 21:16:09 2016] Processing stm32f103c8t6 (platform: ststm32, board: bluepill_f103c8, framework: arduino)
-------------------------------------------------------------------------------------------------------------------------------------------------
Collected 24 compatible libraries
Looking for dependencies...
Project does not have dependencies
MethodWrapper(["upload"], [".pioenvs/stm32f103c8t6/firmware.bin"])
Auto-detected: /dev/cu.SLAB_USBtoUART
/Users/gook/.platformio/packages/framework-arduinoststm32/tools/macosx/ /dev/cu.SLAB_USBtoUART /Users/gook/Projects/arduino_ST32/.pioenvs/stm32f1
03c8t6/firmware.bin
sh: /Users/gook/.platformio/packages/framework-arduinoststm32/tools/macosx/: is a directory
*** [upload] Error 126
```

**Comment by ivankravets** [comment]
@justgook Could you try `board = stm32f103c8t6` instead `board = bluepill_f103c8`?

**Comment by justgook** [comment]
Error: Unknown board ID 'stm32f103c8t6'

**Comment by ivankravets** [comment]
@justgook please sorry, it should be `board = genericSTM32F103C8`

**Comment by justgook** [comment]
Totally same result:
```
gook@work:~/Projects/arduino_ST32⚡pio run -v --target upload
[Tue Oct 11 00:16:14 2016] Processing stm32f103c8t6 (platform: ststm32, board: genericSTM32F103C8, framework: arduino)
-----------------------------------------------------------------------------------------------------------------------------------------
Collected 24 compatible libraries
Looking for dependencies...
Project does not have dependencies
MethodWrapper(["upload"], [".pioenvs/stm32f103c8t6/firmware.bin"])
Auto-detected: /dev/cu.SLAB_USBtoUART
/Users/gook/.platformio/packages/framework-arduinoststm32/tools/macosx/ /dev/cu.SLAB_USBtoUART /Users/gook/Projects/arduino_ST32/.pioenvs
/stm32f103c8t6/firmware.bin
sh: /Users/gook/.platformio/packages/framework-arduinoststm32/tools/macosx/: is a directory
```

**Comment by ubis** [comment]
You need to set upload protocol in platformio ini. For example, if you want to use STM32 serial, you need to write this line into platformio.ini:

`upload_protocol = serial`
or if using dfu:
`upload_protocol = dfu`

**Comment by justgook** [comment]
btw is there somewhere DFU manual - how to enable it and how to use it ?

**Comment by ubis** [comment]
You just need to set upload protocol as dfu and it should be fine.
Although there are some issues with older dfu/maple revisions and we didn't solved it yet.

**Comment by justgook** [comment]
need to check later at home..

**Comment by fabriciopk** [comment]
I upload the .bin(.pioenvs/stm32f103c8t6/firmware.bin) using openocd and stlink and now I can't re-flash the board. The swd is disable during the build?

**Comment by ivankravets** [comment]
@ubis that is not good workflow. Some protocol should be set by default when user didn't specify it.
Which protocol we can use by default?

**Comment by ubis** [comment]
Yeah, actually I had "serial" protocol as default back then, but I removed it when it was merged into this repo. So yeah, "serial" protocol could be used by default.

**Comment by ivankravets** [comment]
Thanks, I'll fix it.

I'm just working on refactoring the support for Arduino/stm32. Need to move all tools from framework package to own OS related packages where our package manager will automatically handle them.

I'll report here about results.

**Comment by ivankravets** [comment]
Development platform will be released today.

**Comment by justgook** [comment]
just downloaded `develop` branch and got error (but looks good)

```
pio run -v --target upload
[Tue Oct 11 23:10:12 2016] Processing stm32f103c8t6 (platform: ststm32, board: genericSTM32F103C8, framework: arduino)

-------------------------------------------------------------------------------------------------------------------------------------------------
Collected 25 compatible libraries
Looking for dependencies...
Project does not have dependencies
MethodWrapper(["upload"], [".pioenvs/stm32f103c8t6/firmware.bin"])
Auto-detected: /dev/cu.SLAB_USBtoUART
/Users/gook/.platformio/packages/framework-arduinoststm32/tools/macosx/serial_upload /dev/cu.SLAB_USBtoUART {upload.altID} {upload.usbID} /Users/
gook/Projects/arduino_ST32/.pioenvs/stm32f103c8t6/firmware.bin /Users/gook/Projects/arduino_ST32/.pioenvs/stm32f103c8t6/firmware.bin
Cannot handle device "/dev//dev/cu.SLAB_USBtoUART"
stm32flash Arduino_STM32_0.9

http://github.com/rogerclarkmelbourne/arduino_stm32

Using Parser : Raw BINARY

Failed to open port: /dev//dev/cu.SLAB_USBtoUART
*** [upload] Error 1
```

**Comment by ivankravets** [comment]
@justgook this issue is related with https://github.com/platformio/platform-ststm32/issues/9

**Comment by ivankravets** [comment]
@justgook  could you re-test the latest dev version? https://github.com/platformio/platform-ststm32/issues/9#issuecomment-253068416

**Comment by justgook** [comment]
im at work - i can test it when ill get home

**Comment by ivankravets** [comment]
PIO Remote will resolve this issue and will allow to work with home's hardware from a work 😊
