### ISSUE TITLE
New Board Request: GTM32 Pro

### ISSUE THREAD

**Issue by AlexanderAmelkin** [platformio/platform-ststm32#145]
Hi. Could you please add "Geetech GTM32 Pro" board? It's basically a genericSTM32F103VE board with one difference: it does NOT have a USB serial port on PA11 and PA12 pins. Instead they are used as GPIO. Thus, genericSTM32F103VE doesn't work for that board or I am unaware of the method to properly remove `-DSERIAL_USB` and set `#define BOARD_HAVE_SERIALUSB 0` for this board to disable initialization of USB.

Please either add the board or tell how to undefine `SERIAL_USB` and define `BOARD_HAVE_SERIALUSB` to 0 from `platormio.ini` or any other way at project configuration level.

Thank you.

**Comment by ivankravets** [comment]
It should work with the latest upstream version https://docs.platformio.org/en/latest/platforms/ststm32.html#upstream

Could you try `genericSTM32F103VE`?

**Comment by ivankravets** [comment]
Please reopen if you still need help
