### ISSUE TITLE
STM32H7 support

### ISSUE THREAD

**Issue by eeyurdakul** [platformio/platform-ststm32#150]
How can I make stm32h7 working in stm32cube framework manually?
Is there going to be an update for this framework?

**Comment by ivankravets** [comment]
What is your board? Custom?

**Comment by eeyurdakul** [comment]
Nucleo-H743ZI
https://www.st.com/en/evaluation-tools/nucleo-h743zi.html

**Comment by valeros** [comment]
Please re-test with the upstream version http://docs.platformio.org/en/latest/platforms/ststm32.html#upstream
