### ISSUE TITLE
Add support for SDIO on mbed-os

### ISSUE THREAD

**Issue by masoudr** [platformio/platform-ststm32#152]
Hi,
I found that there are some works on adding SDIO SDFileBlock to new versions of `mbed-os 5.9` and higher. I think it might be a good idea to add it. I tested the library and worked fine on STM32F407VE.
[Here](https://github.com/ARMmbed/mbed-os/issues/6384) is the issue on `mbed-os` repo and the [fork ](https://github.com/JojoS62/mbed-os)of developer itself.
Thanks.

**Comment by bmcdonnell-ionx** [comment]
How does this issue differ from #6384, which you also linked above? I see you already closed #8450 on the same.
