### ISSUE TITLE
Upload using openocd and stlinkv2

### ISSUE THREAD

**Issue by fabriciopk** [platformio/platform-ststm32#16]
I upload the .bin(.pioenvs/stm32f103c8t6/firmware.bin) using openocd and stlink and now I can't re-flash the board. The swd is disable during the build?

Code:
https://github.com/fabriciopk/SEA_Firmware

**Comment by ivankravets** [comment]
@ubis, please help us.

**Comment by ubis** [comment]
I'm not really familiar with SWD and stuff, maybe you used some different flags?
Could you try to reflash firmware with ROM bootloader?

**Comment by fabriciopk** [comment]
I upload the code using openocd with the same script that I use for others binaries, and it always work. But when I flash with the binaries that I build using platformio, the stlink not recognize the microcontroler any more. 
It's possible to use platformio to upload the binaries using stlink? I was reading about adding in the platformio.ini

UPLOAD_PROTOCOL = stlink

**Comment by ivankravets** [comment]
@fabriciopk please re-test the latest dev build:
```
pio platform uninstall ststm32
pio platform install https://github.com/platformio/platform-ststm32/archive/develop.zip
```

Does it work?

**Comment by ivankravets** [comment]
@fabriciopk do you have any news?

**Comment by ivankravets** [comment]
Please reopen if you still have problems
