### ISSUE TITLE
Support ARM GCC toolchain for STM32F0

### ISSUE THREAD

**Issue by AntoinedeChassey** [platformio/platform-ststm32#162]
It would be nice to integrate the GCC framework.

Link:
- https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads

**Comment by ivankravets** [comment]
We already support GCC toolchain

**Comment by AntoinedeChassey** [comment]
@ivankravets thank you for your response.
Is there a link to some docs about this ? I could not manage to find how to flash an STM32F04266
Thx

**Comment by ivankravets** [comment]
Do you mean this https://docs.platformio.org/en/latest/boards/ststm32/nucleo_f042k6.html?
