### ISSUE TITLE
STM32F303CBT6 Support?

### ISSUE THREAD

**Issue by glynhudson** [platformio/platform-ststm32#177]
Hi, 

Would it be possible to add support for STM32F303CBT6? It's very similar to other MCU's supported by pio but with some extra pins:

https://uk.farnell.com/stmicroelectronics/stm32f303cbt6/mcu-32bit-cortex-m4-72mhz-lqfp/dp/2333254

https://datasheet.octopart.com/STM32F303CBT6-STMicroelectronics-datasheet-13725529.pdf

We're using this chip for new OpenEnergyMonitor hardware, it would be really great to be able to continue developing using platformio 

Cc. @trystanlea @danbates2

**Comment by ivankravets** [comment]
Hi Glyn,

Which framework do you use? Arduino?

**Comment by TrystanLea** [comment]
Hello @ivankravets we are using stm32cube, thanks for your quick reply.

**Comment by valeros** [comment]
Hi @glynhudson @TrystanLea ! New `genericSTM32F303CB` board has been added. Would be great if you test it with your project. Just install ststm32 platform from dev branch.

**Comment by ivankravets** [comment]
See https://docs.platformio.org/en/latest/platforms/ststm32.html#upstream

**Comment by TrystanLea** [comment]
Thanks @valeros @ivankravets really appreciated

**Comment by glynhudson** [comment]
Wow, that was quick! Thanks a lot of guys. We'll try to test as soon as possible. I'm assuming we will need to install the dev version of Pio?

**Comment by glynhudson** [comment]
Woop woop! That works great. Thanks a lot guys :+1: 

I've added a `platfromio.ini` to our project:

https://github.com/openenergymonitor/STM32/commit/96b0176eb424e00c3b7c6e62f95b6508e65c4cde

**Comment by Zdenko-Stanec** [comment]
Hi, 

Is it possible to add support for the Arduino framework for this MCU?

Thank you,
