### ISSUE TITLE
BOARD_NAME define conflicts with Marlin

### ISSUE THREAD

**Issue by ktand** [platformio/platform-ststm32#181]
In the latest release there is a `BOARD_NAME` defined in the GCC command line. Unfortunately this conflicts with the `BOARD_NAME` definition in the Marlin project (https://github.com/MarlinFirmware/Marlin)

**stm32duino.py**

```
    CPPDEFINES=[
        series,
        "HAL_UART_MODULE_ENABLED",
        ("ARDUINO", 10805),
        ("ARDUINO_%s" % variant),
        ("ARDUINO_ARCH_STM32"),
        ("BOARD_NAME", variant),
        env.BoardConfig().get("build.variant", "").upper()
    ],
```

I think it was introduced when support for Arduino Core STM32 was added (https://github.com/platformio/platform-ststm32/pull/151)

What is the usage for the `BOARD_NAME` define? Is it needed or could it be removed or renamed?

Regards,
Karl

**Comment by fpistm** [comment]
Hi @ktand ,  this is not linked to pio. This is one defined by the core:
https://github.com/stm32duino/Arduino_Core_STM32/commit/ca62452122d7da8ac08e2b2212fc899575fbe31d
It was requested by several users to know the board name.

**Comment by ktand** [comment]
Hi @fpistm

Ok, I understand. However it seems like BOARD_NAME is defined like:

-DEXAMPLEBOARD -DBOARD_NAME=EXAMPLEBOARD

I thiink there should at least be quotes around -DBOARD_NAME, like:

-DEXAMPLEBOARD -DBOARD_NAME="EXAMPLEBOARD"

Regards,
Karl

**Comment by fpistm** [comment]
Right it's a string.

**Comment by ktand** [comment]
When I compile with PlatformIO it's defined as:

-DARDUINO_ARMED_V1 -DARDUINO_ARCH_STM32 -DBOARD_NAME=ARMED_V1 -DARMED_V1

Notice the missing quotation marks.

Karl

**Comment by ivankravets** [comment]
Just use  https://docs.platformio.org/en/latest/projectconf/section_env_build.html#build-unflags
```
[env:myenv]
board = ...
build_unflags = -DBOARD_NAME=ARMED_V1
```

Did it help?

**Comment by ktand** [comment]
@ivankravets 
@fpistm

Yes, sure it will help but why isn't BOARD_NAME defined as a string?

An example, for the board variant "ARMED_V1" the compiler will be invoked with:

-DARDUINO_ARMED_V1 -DARDUINO_ARCH_STM32 -DBOARD_NAME=ARMED_V1 -DARMED_V1

So BOARD_NAME will be defined as ARMED_V1 which is I assume will be defined as 1.

So BOARD_NAME will be equal to 1, or is my CPP knowledge fading away...? :-)

Sure you can do: 

#ifdef BOARD_NAME but I don't think that was the idea with the BOARD_NAME define as you could have used #ifdef ARMED_V1 instead.

**Comment by ivankravets** [comment]
@fpistm can we remove `BOARD_NAME` macro? Do you depend on it? This is actually something new to Arduino cores.

**Comment by fpistm** [comment]
Don't know how PIO handle platform.txt but with Arduino IDE this is a string.
-DARDUINO_ARMED_V1 -DARDUINO_ARCH_STM32 "-DBOARD_NAME=\"ARMED_V1\"" -DSTM32F407xx

So, I guess this is an issue how PIO parse it as this is not the same behaviour.

**Comment by ivankravets** [comment]
Sorry, it should be fixed in the upstream version of dev/platform. Please re-test. See instruction => https://docs.platformio.org/en/latest/platforms/ststm32.html#stable-and-upstream-versions

**Comment by ktand** [comment]
I can confirm that this is fixed in the upstream version - thanks!
