### ISSUE TITLE
Support blue pill with 128k

### ISSUE THREAD

**Issue by benwaffle** [platformio/platform-ststm32#184]
instead of having to use board `genericSTM32F103CB`, there should be a board `bluepill_f103c8_128k`

stm32duino already supports this with a custom linker script - https://github.com/stm32duino/Arduino_Core_STM32/blob/master/variants/BLUEPILL_F103C8/ldscript_cb.ld

so I believe this line needs to be changed: https://github.com/platformio/platform-ststm32/blob/develop/builder/frameworks/arduino/stm32duino.py#L176

**Comment by benwaffle** [comment]
The current problem with using `genericSTM32F103CB` is that [variant.h](https://github.com/stm32duino/Arduino_Core_STM32/blob/master/variants/MAPLEMINI_F103CB/variant.h) is not accurate (e.g. LED_BUILTIN is listed as `PB1` which may be correct on a real F103CB but is actually `PC13` on a F103C8)

**Comment by fpistm** [comment]
FYI, ldscript will be reviewed as the next release will allow to preprocess linker script file. This means switches are now usable in ld file.
