### ISSUE TITLE
Requesting support for the Hy-Tiny board with the STM32F103TBU6 processor

### ISSUE THREAD

**Issue by mitchmitchell** [platformio/platform-ststm32#188]
What kind of issue is this?

- [X] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

------------------------------------------------------------------

### Configuration

**Operating system**: Ubuntu 18.10

**PlatformIO Version** (`platformio --version`): 1.6.0 (2018-12-12)

### Description of problem
Requesting support for the Hy-Tiny board with the STM32F103TBU6 processor.
This board was just added to the STM32Duino repository via pull request https://github.com/stm32duino/Arduino_Core_STM32/pull/416

### Additional info
http://wiki.stm32duino.com/index.php?title=HY-TinySTM103T
http://www.haoyuelectronics.com/Attachment/HY-TinySTM103T/HY-TinySTM103T_SCH.pdf
http://www.haoyuelectronics.com/Attachment/HY-TinySTM103T/HY-TinySTM103T-Dimensions.png

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platform-ststm32/blob/develop/boards/hy_tinystm103tb.json

**Comment by ivankravets** [comment]
Please re-test with the upstream version https://docs.platformio.org/en/latest/platforms/ststm32.html#stable-and-upstream-versions
