### ISSUE TITLE
Support for mbed 3.127

### ISSUE THREAD

**Issue by douardda** [platformio/platform-ststm32#19]
When will mbed 3.127 be added? 

BTW, is there a way to install (locally) a yet unsupported version of mbed somehow in platformio?

Thanks,

David

**Comment by douardda** [comment]
I'm also wondering if there is a way to use the future mbed-os 5.2 in platformio? I guess  I need to be able to somehow compile my own framework-mbed...

David

BTW platformio is really awesome, thanks

**Comment by ivankravets** [comment]
> BTW, is there a way to install (locally) a yet unsupported version of mbed somehow in platformio?

Please go to `/.platformio/packages/framework-mbed` and unpack ARM mbed source files here. Keep `platformio` folder and `package.json` without changes.

**Comment by douardda** [comment]
Thanks @ivankravets it works with mbed 3.127. 

I also gave a try to mbed-os-5.2 rc3 (which is my true goal here: I want to use the async api that is now available on all nucleo boards, especially the L432KC I'm using for my current project) and the layout of the repository have changed a lot, so the  platforms/ststm32/builder/frameworks/mbed/mbed.py file needs to be adapted. Have anyone already started to work on supporting mbed-os 5.2 ?

David

**Comment by douardda** [comment]
I've been able to compile and upload some examples on a nucleo board using current mbed head (ie. something like mbed-os 5.2 rc3).  The serial examples is unstable (the device hang if I send chars too quickly) but that's probably an mbed-only pb. 

I'll try to push my code, but I'm pretty sure it's not correct.

**Comment by douardda** [comment]
Ok I've pushed my code on https://github.com/douardda/builder-framework-mbed/tree/mbed-5.2

Note sure I should make a PR with this, more polishing might be necessary.

**Comment by ivankravets** [comment]
Thanks a lot for your PR. Please keep it alive. We will back to it after 5.2 release.

**Comment by douardda** [comment]
Ok so let me create a proper PR with my branch even if it will most probably require some more work.

**Comment by douardda** [comment]
Hi, one more question: what is the code responsible for generating the eix files? They look generated from (at least) targets.json, and I'd like to update them for mbed 5.2, and there seems to be a small bug making flags duplicated several times).

**Comment by ivankravets** [comment]
@douardda Please check `~/.platformio/packages/framework-mbed/platformio/README.txt`

**Comment by douardda** [comment]
Sorry I missed this README file... thanks @ivankravets!

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platform-ststm32/commit/40dc0b3e970b9a5279db567e6ebe8e135c748b3d
