### ISSUE TITLE
Request: Add an option to use CMSIS 5.0 with the CMSIS framework with ST STM32 platform

### ISSUE THREAD

**Issue by vshashi01** [platformio/platform-ststm32#190]
Currently, the CMSIS framework initialization stil only results in the CMSIS V4 libraries  available within the framework. It would be nice, if the PlatformIO CMSIS framework also include the new and improved[ CMSIS 5.0](https://github.com/ARM-software/CMSIS_5/tree/master) that could be very interesting for new and advanced development with CMSIS framework coupled with ST STM32 platform. I think a simple platformio.ini option to set which version to include could be useful for users who wish to have both option, since much of the legacy project may still exist in previous version of CMSIS.

**Comment by frankleonrose** [comment]
Current framework-cmsis/README.md indicates CMSIS Version 5.4.0. Can this be marked closed, @ivankravets?

**Comment by ivankravets** [comment]
Thanks!
