### ISSUE TITLE
Mbed framework DFU support

### ISSUE THREAD

**Issue by me21** [platformio/platform-ststm32#192]
There are similar issues concerning DFU support in official STM32 Arduino core: #191, #183. Mbed framework doesn't support DFU upload protocol either.

Since all that is needed for DFU support is alternative linker script, I think it can be added even without altering upstream Mbed repo. But even if not, the fix is pretty straightforward. Just add a bunch of linker scripts and pass another option to the linker.

**Comment by me21** [comment]
I forgot about interrupt controller configuration. It should use interrupts table at another address with dfu bootloader. So it can't work with linker script alone, it requires editing Mbed framework sources (startup routines).

**Comment by me21** [comment]
I've noticed Mbed supports bootloaders in its configuration (`mbed_app.json`). See https://os.mbed.com/docs/mbed-os/v5.11/tutorials/bootloader.html.
The bootloader for DFU protocol with added `platformio.ini` file is located at https://github.com/rogerclarkmelbourne/STM32duino-bootloader/pull/49. So it could be built on demand or prebuilt and stored in STM32 platform assets.

Now that STM32 platform supports `mbed_app.json` file, it should be possible to setup the bootloader usage.

**Comment by me21** [comment]
I confirm that Mbed can work with DFU bootloader. But I had no luck configuring it in `mbed_app.json` file yet. I had to manually patch linker script (offset the flash start and size).

**Comment by valeros** [comment]
Should be fixed in the latest release.
