### ISSUE TITLE
increased the size of the firmware

### ISSUE THREAD

**Issue by nikantovik** [platformio/platform-ststm32#196]
very much increased the size of the firmware (((

#include <mbed.h>
int main() {
DigitalOut led (PC_13);
while(1) {
led=1;
wait_ms (100);
led=0;
wait_ms (100);
}
}
Building .pioenvs/genericSTM32F103C8/firmware.bin
Memory Usage -> http://bit.ly/pio-memory-usage 1
DATA: [== ] 17.7% (used 3616 bytes from 20480 bytes)
PROGRAM: [===== ] 50.9% (used 33380 bytes from 65536 bytes)

Why?

**Comment by valeros** [comment]
Might be usefult https://github.com/platformio/platform-ststm32/issues/195#issuecomment-463344386

**Comment by ivankravets** [comment]
https://github.com/platformio/platform-ststm32/issues/195#issuecomment-463344386
