### ISSUE TITLE
version 5.0, use arduino framework Compile failed genericSTM32F103C8

### ISSUE THREAD

**Issue by chengxg** [platformio/platform-ststm32#198]
Linking .pioenvs\genericSTM32F103C8\firmware.elf
.pioenvs\genericSTM32F103C8\libFrameworkArduino.a(syscalls.c.o): In function `_sbrk':
syscalls.c:(.text._sbrk+0x38): undefined reference to `_Min_Stack_Size'
.pioenvs\genericSTM32F103C8\libFrameworkArduino.a(syscalls.c.o):(.data.heap_end.7737+0x0): undefined reference to `_end'
collect2.exe: error: ld returned 1 exit status
*** [.pioenvs\genericSTM32F103C8\firmware.elf] Error 1

**Comment by ljubomirb** [comment]
I am also seeing this on the same board.
I don't know if this is connected with "update platforms" that I clicked, as appose to fresh install, or some other problem. But, as a temporary solution, you can uninstall v5.0 and install v4.6. That version works.
