### ISSUE TITLE
version 5.0, using mbed framework the C++ Tips Failure

### ISSUE THREAD

**Issue by chengxg** [platformio/platform-ststm32#199]
The c++ prompt is invalid as long as "# include < mbed.h>" is referenced.
![image](https://user-images.githubusercontent.com/21291106/52985228-db5d2c80-342d-11e9-923a-58a9aa739d31.png)

vscode output errors:
[Error - 上午9:52:10] Connection to server got closed. Server will not be restarted.
[Error - 上午9:52:10] Request textDocument/definition failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\24960\.vscode\extensions\ms-vscode.cpptools-0.21.0\node_modules\vscode-jsonrpc\lib\main.js:876:25) ...

**Comment by ivankravets** [comment]
It seems like VSCode issue. How to reproduce it?

**Comment by chengxg** [comment]
> It seems like VSCode issue. How to reproduce it?

I don't know,but I tried v4.6 without this problem.

**Comment by ivankravets** [comment]
@valeros Please help.

**Comment by ivankravets** [comment]
Fixed in the latest release. Please open PIO IDE Terminal and type `pio update`. Restart IDE.
