### ISSUE TITLE
mbed_app.json parameters are not honored

### ISSUE THREAD

**Issue by me21** [platformio/platform-ststm32#200]
I'm trying to configure my application for mbed framework with `mbed_app.json` file. Specifically, I need to set the application start address and application maximal size to use it with bootloader.

I followed mbed documentation at https://os.mbed.com/docs/mbed-os/v5.11/reference/bootloader-configuration.html.

Here's my `mbed_app.json` contents:
```
{
    "target_overrides": {
        "*": {
            "target.mbed_app_start": "0x08002000",
            "target.mbed_app_size": "0x1E000"
        }
    }
}
```

The resulting bin file is the same as without any configuration. The uploaded firmware doesn't work.

If I edit the corresponding linker script manually (it is located in the target subfolder of mbed framework), e.g.

```
/* Linker script to configure memory regions. */
/* 0xEC reserved for vectors - 8byte aligned = 0xF0 */
MEMORY
{ 
  FLASH (rx) : ORIGIN = 0x08002000, LENGTH = 128K - 0x2000
  RAM (rwx) : ORIGIN = 0x200000F0, LENGTH = 20K - (0xEC+0x4)
}
```
, it works.

I wanted to attach verbose build output, but it didn't fit into Platformio terminal window. Can it be redirected to file?

**Comment by valeros** [comment]
Hi @me21! That's strange. What is your board? Does your board support bootloader option? Could you try something like this:
```
{
    "target_overrides": {
        "*": {
            "target.mbed_app_start": "0x08002000",
            "target.mbed_app_size": "0x1E000",
            "target.bootloader_supported": true
        }
    }
}
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
