### ISSUE TITLE
STM32F429 support

### ISSUE THREAD

**Issue by behlulgoker** [platformio/platform-ststm32#212]
- [ ] **Feature Request**.
      Please add STM32F429 to the supported boards list.

**Comment by valeros** [comment]
Hi @behlulgoker ! What board exactly? We already have `nucleo_f429zi`

**Comment by behlulgoker** [comment]
Hi @valeros .
It is stm32f429ZIT Discovery.

**Comment by valeros** [comment]
`disco_f429zi` board is already supported https://docs.platformio.org/en/latest/boards/ststm32/disco_f429zi.html
