### ISSUE TITLE
Black Pill board variant - deliberate or copy/paste error?

### ISSUE THREAD

**Issue by pfeerick** [platformio/platform-ststm32#220]
Just noticed when looking at the black pill boards files that the `variant` is `BLUEPILL_F103XX` for both of the F103 boards (but the other black_ boards seems fine / are BLACKXXX)... is that a deliberate choice or a copy/paste error?  Happy to do a PR to correct that.

https://github.com/platformio/platform-ststm32/blob/8fdf59a24b4a77dd984ec98379ebe491e82f1d11/boards/blackpill_f103c8.json#L19

https://github.com/platformio/platform-ststm32/blob/8fdf59a24b4a77dd984ec98379ebe491e82f1d11/boards/blackpill_f103c8_128.json#L19

**Comment by aster94** [comment]
Should be the same, the two F1 blue and black boards are exactly the same while the bigger board (F4 blue/black) are different. Really once existed also the F1 red pill but i think that there are not more on aliexpress 🤔

**Comment by pfeerick** [comment]
Other than having a different pinout and that the builtin led is on different pins ;) Both the red and blue variants had it on PC13, but the black variant is on PB12 ... just to be different... :confused: But other than that minor detail, they are the same - programming-wise anyway.

**Comment by aster94** [comment]
You are right i forgot about the built in led, maybe it is enough to requiere a different board variant!

**Comment by valeros** [comment]
The `variant` field for this board is set according to the [original value in the framework](https://github.com/stm32duino/Arduino_Core_STM32/blob/master/boards.txt#L627).
