### ISSUE TITLE
HardwareTimer not available... what to use?

### ISSUE THREAD

**Issue by silardg** [platformio/platform-ststm32#222]
I have been using HardwareTimer last year for a project.

Now it won't compile with the same code and I haven't found a solution.

I need the interrupt execution of a function every 10ms.

Any suggestions?

**Comment by valeros** [comment]
Hi @silardg ! What board are you using? Probably you need to [switch to the maple core](http://docs.platformio.org/en/latest/platforms/ststm32.html#switching-between-arduino-cores).

**Comment by silardg** [comment]
@valeros 

I have fixed it by switching to version 2.0.0 :/

I don't have time to debug it, but it works like this. 

I would suggest not closing this issue, maybe someone finds an easy workaround to having HardwareTimer.
