### ISSUE TITLE
Location of 'platformio-build.py' script?

### ISSUE THREAD

**Issue by SJ-Innovation** [platformio/platform-ststm32#233]
Hi,
Im looking at making a couple of minor changes to platformio-build.py (packages/framework-arduinoststm32/tools/platformio-build.py) which is available from the CDN packaged versions of the framework that platformio downloads and uses ([Here](https://bintray.com/platformio/dl-packages/framework-arduinoststm32)).

However, I cant for the life of me find where this file is developed as I cant find the 'tools' directory anywhere in this repo! I have searched high and low for where this damn file comes from but i'm at a bit of a wits end [Hense why I'm asking here... I don't know where else]... I don't suppose you could lend an insight could you? 

Thanks, and all the best! 
-Sam

**Comment by valeros** [comment]
Hi @SJ-Innovation! Sorry for the late reply. The latest build scripts you can find [here](https://github.com/platformio/builder-framework-mbed/tree/feature/mbed-api-based-builder).
