### ISSUE TITLE
dfu-util x64 on i386 system

### ISSUE THREAD

**Issue by mrdROb** [platformio/platform-ststm32#235]
Just faced an issue while using old i386 Debian Linux laptop
When trying to upload the code to stm32f103 by using DFU mode I am getting the error:
"... cannot execute ~/platformio/...../dfu-util - Format exec error ..."
The dfu-util is there but I can not launch it. Looks like it is not for my outdated architecture,

What would be the correct solution? ( I am going to replace the utility with Symlink for the working dfu-util from my distribution as a temporary solution)

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platform-ststm32/pull/630
