### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by bms1050428813** [platformio/platform-ststm32#238]
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\ASUS\\Documents\\PlatformIO\\Projects\\car\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError:"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platform-ststm32/issues/232
