### ISSUE TITLE
mbed Framework for ST Nucleo H743ZI and H743ZI2

### ISSUE THREAD

**Issue by lhcavalcanti** [platformio/platform-ststm32#279]
Hello,
Recently I bought an ST Nucleo H743ZI2, and as I have been using Platformio with ST boards thru mbed framework, I also tried to use mbed thru Platformio to the new ST H743ZI2. 

Sadly I discovered that Platformio doesn't support mbed framework for H743 boards. 
So I took a look at mbed releases and since the [mbed-os-5.13.1](https://github.com/ARMmbed/mbed-os/releases/tag/mbed-os-5.13.1) release they support both ST H743ZI boards.
Do you guys plan to support ST H743 boards soon? 
Thanks!

**Comment by valeros** [comment]
Thanks for the info. Now you can use mbed framework with board `nucleo_h743zi` (for both H743ZI and H743ZI2).
