### ISSUE TITLE
CMSIS-DAP support for Generic STM32 Boards

### ISSUE THREAD

**Issue by hez2010** [platformio/platform-ststm32#287]
I modified `genericSTM32F407VET6.json` manually and append "cmsis-dap" in `protocols` section.
![image](https://user-images.githubusercontent.com/14960345/65257851-7d640500-db34-11e9-816c-22e462bd1700.png)

And I edit platformio.ini:
```ini
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
```

Then I build and successfully upload the built firmware to my board.
![image](https://user-images.githubusercontent.com/14960345/65258047-d3d14380-db34-11e9-9594-e95792994f82.png)

I think you can add the cmsis-dap support for Generic STM32 boards.

My platformio.ini:
```ini
[env:genericSTM32F407VET6]
platform = ststm32
board = genericSTM32F407VET6
framework = cmsis
test_transport = custom
debug_tool = cmsis-dap
upload_protocol = cmsis-dap
lib_extra_dirs = .
build_flags = 
    -fexceptions
    -DUSE_STDPERIPH_DRIVER
```

**Comment by jxltom** [comment]
Hey thanks for sharing.

Can you make the debug with cmsis-dap working?

**Comment by jxltom** [comment]
For me, error is ```Error: Unknown debug tool `cmsis-dap`. Please use one of `jlink, stlink` or `custom````

**Comment by hez2010** [comment]
It worked fine previously, but I have no idea about how it's going now since currently I'm not working with IoT development.

**Comment by jxltom** [comment]
Ok, thanks for reply anyway.

**Comment by gitneko** [comment]
The documentation to CMSIS-DAP debugging is quite misleading. I'm trying to use `cmsis-dap` as `debug_tool` as instructed by the documentation (<https://docs.platformio.org/en/v5.0.1/plus/debug-tools/cmsis-dap.html>) but it leads to a python error when trying to rebuild intelisense index:
```
DebugInvalidOptionsError: Unknown debug tool `cmsis-dap`. Please use one of `atmel-ice, blackmagic, jlink` or `custom`:
```

Fresh PlatformIO installation with Atmel SAM platform and Arduino MKR1000 board.

Core: v5.0.1
Home: v3.3.0

Is there something that I need to have installed to make this work?

**Comment by 424778940z** [comment]
> For me, error is `` Error: Unknown debug tool `cmsis-dap`. Please use one of `jlink, stlink` or `custom ``

you guys all missed the important part lol

"I modified genericSTM32F407VET6.json manually and append "cmsis-dap" in protocols section."

You HAVE TO edit the board define file.
