### ISSUE TITLE
Debug breakpoint is not followed at MBED

### ISSUE THREAD

**Issue by SuperBoss9** [platformio/platform-ststm32#289]
Hello everyone,

I found out that PIO doesn't stop at MBED breakpoint. For example, I use NUCLEO STM32F103RB if I set up a breakpoint then Debugger doesn't stop at the brekapoint. Instead of that it stops at the beginning of main function.
Then I can debug more or less well but if I continue execution of the program via "play" then debugger doesn't stop at the breakpoint again.

PS. Mbed Studio works well with its debugger and it can stop at my breakpoints.

**Comment by valeros** [comment]
That's strange, breakpoint at main function is only temporary, you can disable it by specifying the following:
```
[env:debug]
platform = ...
board = ...
debug_init_break =
```

**Comment by SuperBoss9** [comment]
Didn't help. Debugging started from main. But then after re-run it stopped at my breakpoint.
![image](https://user-images.githubusercontent.com/53711021/65574350-ebb22880-df75-11e9-965f-1c72045ce18d.png)

First stop at a "reset handler" then at the first string of main then at my breakpoint.

Test the same with Arduino. Absolutely equal behaviour.

It seems that it work at this machine.
