### ISSUE TITLE
Having a Windows username that contains spaces causes project building to fail

### ISSUE THREAD

**Issue by mah-qurashy** [platformio/platform-ststm32#298]
trying to build stm32 project on windows, building fails and reports that a linker file does not exist.
the file actually exists, but the path appearing in the error is actually incomplete, my username contains a space so the part of the path before the space is missing

> Verbose mode can be enabled via -v, --verbose option
> CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/nucleo_f446re.html
> PLATFORM: ST STM32 5.6.0 > ST Nucleo F446RE
> HARDWARE: STM32F446RET6 180MHz, 128KB RAM, 512KB Flash
> DEBUG: Current (stlink) On-board (stlink) External (blackmagic, jlink)
> PACKAGES: toolchain-gccarmnoneeabi 1.70201.0 (7.2.1), framework-stm32cube 2.0.181130
> LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
> LDF Modes: Finder ~ chain, Compatibility ~ soft
> Found 29 compatible libraries
> Scanning dependencies...
> No dependencies
> Linking .pio\build\nucleo_f446re\firmware.elf
> arm-none-eabi-gcc: error: Qurashy\.platformio\packages\framework-stm32cube\platformio\ldscripts\STM32F446RE_FLASH.ld: No such file or directory
> *** [.pio\build\nucleo_f446re\firmware.elf] Error 1
> ======================================================== [FAILED] Took 14.53 seconds ========================================================
> The terminal process terminated with exit code: 1
> 
> Terminal will be reused by tasks, press any key to close it

**Comment by valeros** [comment]
Should be fixed in the latest `platformio-core`. Please switch to [development version](http://docs.platformio.org/en/latest/ide/vscode.html#platformio-ide-usedevelopmentpiocore) and try again. Thanks!
