### ISSUE TITLE
missing "variant.h" for boards "netduino" or "stm32f4stamp" when using stm32 core

### ISSUE THREAD

**Issue by mik-p** [platformio/platform-ststm32#303]
using maple core with stm32f4stamp board works but is limited, as in Wire and SD libraries do not exist. tried to use stm32 build core instead and it does not compile.

`
framework-arduinoststm32\system\STM32F4xx/stm32f4xx_hal_conf.h:4:10: fatal error: variant.h: No such file or directory
`

**Comment by valeros** [comment]
Unfortunately, this board is not supported by STM32 core. You'd better open an issue in their [repository](https://github.com/stm32duino/Arduino_Core_STM32/issues).
