### ISSUE TITLE
[FR] Please update Arduino_Core_STM32 to latest version

### ISSUE THREAD

**Issue by LinoBarreca** [platformio/platform-ststm32#304]
We need SoftwareSerial as we specify here
https://github.com/teemuatlut/TMCStepper/issues/75
and it has already been merged here
https://github.com/stm32duino/Arduino_Core_STM32/pull/645
on sept 11.

Thanks

**Comment by valeros** [comment]
Hi @LinoBarreca ! It's already updated but not yet released. You can try with upstream version:
```
[env:upstream_develop]
platform = https://github.com/platformio/platform-ststm32.git
board = ...
```
