### ISSUE TITLE
Add support for stm32duino in Generic STM32F103Rx 

### ISSUE THREAD

**Issue by miuirussia** [platformio/platform-ststm32#307]
They now officialy supported:

https://github.com/stm32duino/Arduino_Core_STM32/commit/f49877a3865d55c757b476eeec6cb33438bd8cb2

**Comment by valeros** [comment]
Hi @miuirussia ! Generic `F103Rx` boards are already available but with `maple` core by default. If you want to use them with `stm32duino core you can try the following configuration:
```
[env:genericSTM32F103RB]
platform = ststm32
framework = arduino
board = genericSTM32F103RB
board_build.variant = Generic_F103Rx
board_build.core = stm32
```
