### ISSUE TITLE
Support for Adafruit STM32F405 Feather Express

### ISSUE THREAD

**Issue by GH15ADF** [platformio/platform-ststm32#321]
Adafruit added a STM32F405 Feather board. Please add support.
https://learn.adafruit.com/adafruit-stm32f405-feather-express

**Comment by chasd00** [comment]
I'm new to platformIO but I believe the board stm32f4stamp.json is almost identical to Adafruit's STM32F405 Express board. I'm not sure about some of the flags

**Comment by valeros** [comment]
Resolved in e7b7fc7ee543977f37d39ab49a2949e5d58a44bf
