### ISSUE TITLE
Board generic STM32F407 not support framework libopencm3

### ISSUE THREAD

**Issue by ejngnng** [platformio/platform-ststm32#336]
when I create a new stm32 project with platformIO IDE VScode,  
Board: "STM32F407VG(192k RAM, 1024k Flash)(Generic)"
Framework only have 3 choices ， Arduino,  CMSIS and  STM32Cube, not support libOpenCM3
Only STM32F1 series support libOpenCM3 framework.

**Comment by valeros** [comment]
Resolved in https://github.com/platformio/platform-ststm32/commit/0bf8d98f1944d76e4b8159962c04969d610c30ab. Please update your platforms via `pio platform update`
