### ISSUE TITLE
Compilation error with framework = cmsis and upload_protocol = dfu

### ISSUE THREAD

**Issue by Trance-Paradox** [platformio/platform-ststm32#346]
platformio.ini:
[env:genericSTM32F103C8]
platform = ststm32
framework = cmsis
board = genericSTM32F103C8
upload_protocol = dfu

error:
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
DATA:    [          ]   0.0% (used 0 bytes from 20480 bytes)
PROGRAM: [          ]   0.4% (used 232 bytes from 65536 bytes)
Adding dfu suffix to firmware.bin
'C:\Users\Surya' is not recognized as an internal or external command,
operable program or batch file.
*** [.pio\build\genericSTM32F103C8\firmware.bin] Error 1
============================================== [FAILED] Took 1.55 seconds ==============================================

**Comment by valeros** [comment]
Hi @Trance-Paradox ! Looks like you have a whitespace character in your username?

**Comment by Trance-Paradox** [comment]
Umm its a small dash

**Comment by valeros** [comment]
Could you please compile your project in verbose mode and attach the log here?

**Comment by Trance-Paradox** [comment]
I can run it in verbose mode but how to store it in a log file?

**Comment by Trance-Paradox** [comment]
[build.log](https://github.com/platformio/platform-ststm32/files/4154691/build.log)
is this what you wanted

**Comment by Trance-Paradox** [comment]
Has anyone checked on it yet?

**Comment by Trance-Paradox** [comment]
I get it now cli is not recognizing my user name folder with space in it 
How can i fix that issue.

**Comment by Trance-Paradox** [comment]
I tried upload_command in the ini folder and put the directory in ' '. It worked but it would be nise it it was included in main file
