### ISSUE TITLE
why use the maple core for stm32?

### ISSUE THREAD

**Issue by KiraVerSace** [platformio/platform-ststm32#359]
ok, i see some cores for stm32 in Arduino platform, but maple is abandoned by the author, why not use some are updating,
like:
https://github.com/stm32duino/Arduino_Core_STM32
https://github.com/rogerclarkmelbourne/Arduino_STM32

else, i use the board nucleo-stm32f411 ,How can i use the other pins that are not define in Arduino, like PC5, PC6 , i dont konw the index of the pin

**Comment by KiraVerSace** [comment]
i dont know

**Comment by valeros** [comment]
You can specify a suitable core in your `platformio.ini`, for example:
```ini
[env:nucleo_f401re]
platform = ststm32
board = nucleo_f401re
framework = arduino
board_build.core = stm32
```
