### ISSUE TITLE
STM32F103RC with more resources

### ISSUE THREAD

**Issue by rippiedoos** [platformio/platform-ststm32#361]
In the 3D printing scene the BigTreeTech SKR Mini E3 is widely used. In the Marlin FW there is even a BTT_SKR_MINI_E3-target, both with 256K and 512K storage (env:STM32F103RC_btt_512K). 

The chip used on these boards is the 512K version of the ST STM32F103RCT6. The SKU with 256K flash has 48K of SRAM, but the model with 384K and 512K has 64K of SRAM. 
https://www.st.com/resource/en/datasheet/stm32f103ze.pdf (page 11)

Would it be possible to create an extra target in PlatformIO of this chip with the upped specs (64k SRAM, 512K flash) or should this be changed in the Marlin-platformio.ini-file to accommodate this increased SRAM size? Something like
```
board.maximum_ram_size = 65536
```

**Comment by valeros** [comment]
Hi @rippiedoos ! 
```ini
board.maximum_ram_size = 65536
```
should work just fine.
