### ISSUE TITLE
File path: Whitespace handling

### ISSUE THREAD

**Issue by KarateBrot** [platformio/platform-ststm32#364]
I'm not quite sure where exactly the problem lies, but somewhere there is an error when handling file path strings that include whitespaces like the spacebar.
More info is in the link provided below.

# Error message
[This is my output when comiling for STM32F405](https://i.imgur.com/mGVq8TY.png)
>The command "C:\Users\Jan" is either incorrect or could not be found.

# What it should be
The real folder structure is ```C:\Users\Jan Post\more white spaces\...```, which includes a spacebar character.

**Comment by valeros** [comment]
Resolved 03241176548e1705aa2fdf1a792da1e57574dd02
