### ISSUE TITLE
Not choosing  stm32duino/Arduino_Core_STM32 core but always maple!

### ISSUE THREAD

**Issue by HamidSaffari** [platformio/platform-ststm32#366]
Hi, I used this config but always compile with maple core and give me errors.
[env:genericSTM32F103RC]
platform = ststm32
board = genericSTM32F103RC
framework = arduino

**Comment by HamidSaffari** [comment]
Said here:  https://docs.platformio.org/en/latest/platforms/ststm32.html#switching-between-arduino-cores 
"By default, official STM32Duino core is used".
but you have to add this too:  board_build.core = STM32Duino

**Comment by HamidSaffari** [comment]
not I got "fatal error: variant.h: No such file or directory".
How can I choose my STM32 board variant?

**Comment by valeros** [comment]
Hi @HamidSaffari ! You need tto use:
```
board_build.core = stm32
```
