### ISSUE TITLE
Mistake in the last release 6.1.0

### ISSUE THREAD

**Issue by fpistm** [platformio/platform-ststm32#369]
Hi @valeros 
in the last release note ([6.1.0](https://github.com/platformio/platform-ststm32/releases/tag/v6.1.0)
there is a mistake:

> * Updated Arduino Adafruit core to v1.8.0 (release notes)

This is not linked to Adafruit
```patch
- * Updated Arduino Adafruit core to v1.8.0 (release notes)
+ * Updated Arduino STM32 core to v1.8.0 (release notes)
```

**Comment by valeros** [comment]
Many thanks, fixed!
