### ISSUE TITLE
nucleo_l476rg stlink upload help wanted

### ISSUE THREAD

**Issue by cgrrty** [platformio/platform-ststm32#376]
Compiling .pio\build\nucleo_l476rg\src\main.cpp.o
Linking .pio\build\nucleo_l476rg\firmware.elf
Checking size .pio\build\nucleo_l476rg\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [          ]   0.6% (used 796 bytes from 131072 bytes)
Flash: [          ]   0.7% (used 6912 bytes from 1048576 bytes)
Configuring upload protocol...
AVAILABLE: blackmagic, jlink, mbed, stlink
CURRENT: upload_protocol = stlink
Uploading .pio\build\nucleo_l476rg\firmware.elf
xPack OpenOCD, 64-bit Open On-Chip Debugger 0.10.0+dev (2019-07-17-11:28)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
debug_level: 1

srst_only separate srst_nogate srst_open_drain connect_deassert_srst

Error: libusb_open() failed with LIBUSB_ERROR_NOT_FOUND
Error: open failed
in procedure 'program'
** OpenOCD init failed **
shutdown command invoked

*** [upload] Error 1
=============================================================== [FAILED] Took 14.71 seconds ===============================================================

**Comment by valeros** [comment]
The OpenOCD package has been updated, please update packages via `pio update` and retest.
