### ISSUE TITLE
[Feature Request] CMSIS Framework for STM32F0xx

### ISSUE THREAD

**Issue by Schrolli91** [platformio/platform-ststm32#377]
Hey there,

is there any reason, why PIO has no CMSIS Framework for the STM32F0xx-series?
I can only find the following CMSIS headers from ST in `....platformio\packages\framework-cmsis\variants\ststm32` 
But they provide also CMSIS Headers for the F0-series.

![image](https://user-images.githubusercontent.com/6043382/80572441-8f792080-89fe-11ea-814c-b8406f193ea7.png)

Maybe its possible to bring these heders into PIO.

**Comment by Schrolli91** [comment]
@ivankravets  thanks for transfer to the right repo - sorry for opening in the wrong.
maybe thats a possible duplicate with #26 ?

**Comment by ivankravets** [comment]
Yes,it's duplicate https://github.com/platformio/platform-ststm32/issues/26

We will back soon to https://github.com/platformio/platform-ststm32/issues/26
