### ISSUE TITLE
Wrong JSON file board name

### ISSUE THREAD

**Issue by Nukersson** [platformio/platform-ststm32#383]
The JSON file [disco_h743xi.json](https://github.com/platformio/platform-ststm32/blob/develop/boards/disco_h743xi.json) belongs obviously to disco_h747xi but has wrong name pointing to stm32h743xi. Please fix it.

**Comment by MCUdude** [comment]
The developers are quite busy. For simple fixes like this, for this repo and create a PR. It's very simple!

**Comment by Nukersson** [comment]
> The developers are quite busy. For simple fixes like this, for this repo and create a PR. It's very simple!

Sure. You're right. This ist just reminder currently.
