### ISSUE TITLE
LTO support via GCC AR

### ISSUE THREAD

**Issue by daniel-starke** [platformio/platform-ststm32#386]
Currently, platformio does not play well in combination with the compile/link flag `-flto` (enabled via `build_flags`), which enables link time optimization. This is because the intermediate archive files cannot be created due to the lack of the LTO plugin in binutils' ar. One could work around this by setting the environment variable `AR` accordingly beforehand. This, however, breaks the purpose of platformio of hiding such platform specific configurations from the user. Another way is to use always gcc-ar instead of the plain ar.
I suggest to change `arm-none-eabi-ar` into `arm-none-eabi-gcc-ar` [here](https://github.com/platformio/platform-ststm32/blob/develop/builder/main.py#L29).
Link time optimization can highly improve flash and memory usage of the compiled firmware.

**Comment by valeros** [comment]
Resolved in https://github.com/platformio/platform-ststm32/commit/5d6d2e98ec571bcb10b14901664aed25a01bd818
