### ISSUE TITLE
Feather STM32F405 is supported by Zephyr

### ISSUE THREAD

**Issue by tjpeden** [platformio/platform-ststm32#387]
Would be nice if the Zephyr framework was added to the Feather STM32F405!

**Comment by valeros** [comment]
We tend to support only the stable versions of frameworks. There is no Feather STM32F405 in the list of supported board for the latest stable Zephyr v2.2.0: https://docs.zephyrproject.org/2.2.0/boards/arm/index.html
So I suppose the support for this board will be released with Zephyr v2.3.0.

**Comment by valeros** [comment]
Resolved in https://github.com/platformio/platform-ststm32/commit/a406bacb03f805e250e07f66362c703d605c71f8
