### ISSUE TITLE
Upgrade bundled stlink utility from 1.1 to 1.3

### ISSUE THREAD

**Issue by krish2487** [platformio/platform-ststm32#39]
Hello,

A couple of users (including myself) have faced issues with the bundled stlink utility unable to flash or debug the compiled binaries. I have tried to flash with the 1.3 version binary downloaded from the texane/github page and the binary works as expected.

Can I trouble the platformio team to spend some time upgrading the bundled stlink to 1.3??
It will reduce a couple of issues related to flashing and debugging.

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platform-ststm32/commit/4e4475c9de8f835f3c95bc6ea7f048ec33f25c6f

Could you try the new ST-Link v1.3.1?

1. `pio platform uninstall ststm32`
2. `pio platform install https://github.com/platformio/platform-ststm32.git`

If you already have GIT version fo ST STM32 development platform, then just update it via `pio update`.
