### ISSUE TITLE
Add support for framework libopencm3 for board "ST 32F429IDISCOVERY"

### ISSUE THREAD

**Issue by pwnorbitals** [platformio/platform-ststm32#401]
The board explorer (https://platformio.org/boards) doesn't list it

**Comment by maxgerhardt** [comment]
..Yes it does? https://docs.platformio.org/en/latest/boards/ststm32/disco_f429zi.html#frameworks

**Comment by valeros** [comment]
Resolved in https://github.com/platformio/platform-ststm32/commit/0bf8d98f1944d76e4b8159962c04969d610c30ab. Please update your platform via `pio platform update`.
