### ISSUE TITLE
ststm32 falils to update to 7.1.1 because of a 404 status code

### ISSUE THREAD

**Issue by bibipoggio** [platformio/platform-ststm32#408]
Platform ST STM32
--------
Updating ststm32                         @ 6.1.1          [7.1.1]
Uninstalling ststm32 @ 6.1.1:   [OK]
PlatformManager: Installing ststm32 @ 7.1.1
Warning! Package Mirror: Got an unrecognized status code '404' when downloaded https://dl.registry.platformio.org/download/platformio/platform/ststm32/7.1.1/ststm32-7.1.1.tar.gz
Looking for another mirror...
Warning! Package Mirror: Got an unrecognized status code '404' when downloaded https://dl.registry.platformio.org/download/platformio/platform/ststm32/7.1.1/ststm32-7.1.1.tar.gz
Looking for another mirror...
Error: Could not install 'ststm32' with version requirements '7.1.1' for your system 'windows_x86'.

**Comment by ivankravets** [comment]
Please try again, should work now.

Sorry for the issue.

**Comment by bibipoggio** [comment]
thanks @ivankravets 
just a noob question. I'm trying to build an upgraded version of marlin, but everytime I try to do so the vs code downloads the 6.1.1 version and fails to build it. Is it expected? or should it use the new 7.1.1 version to build it?
![print1](https://user-images.githubusercontent.com/67530680/86825744-1e8d5f00-c066-11ea-830f-c649714693d7.jpg)

**Comment by puzrin** [comment]
@bibipoggio See https://github.com/MarlinFirmware/Marlin/commit/5513e67512481024e0d571d84487f7c636996803. All developers pin dependencies to guarantee stability. You certainly should not try to override that.

If you have build problems with concrete project - ask in Marlin repo or their forum first.
