### ISSUE TITLE
Which commit of Arduino_Core_STM32 is used in the 6.1.1 release?

### ISSUE THREAD

**Issue by Bmooij** [platformio/platform-ststm32#412]
I want to fork Arduino_Core_STM32 repo to make some changes, for my custom hardware.
But because I used version 6.1.1 of platform-ststm32, I wanted to know which commit is used so I can branch it.

First I thought it was the commit for version 1.8.0 (commit [#16f3644](https://github.com/stm32duino/Arduino_Core_STM32/tree/1.8.0)). But that failed.

Then I searched though the build log and found:
framework-arduinoststm32 4.10800.200207 (1.8.0)
But I can't map the 4.10800.200207 to a specified commit.

Then I tried the latest commit for the given day 4.10800.**200207** (February the 7, 2020). But that also failed.

How and/or where can I find the specific commit of the Arduino_Core_STM32 repo that is used in the release of  6.1.1?

**Comment by valeros** [comment]
#16f3644 is the right commit, but it won't work since additional files (CMSIS package and PlatformIO build scripts) need to be shipped together with `Arduino_Core_STM32` in one package. You can take a look at the `framework-arduinoststm32` package and compare with the original `Arduino_Core_STM32`.
