### ISSUE TITLE
Missed remapping entry for STM32F429I-Discovery board.

### ISSUE THREAD

**Issue by puzrin** [platformio/platform-ststm32#413]
Reference: https://community.platformio.org/t/how-in-include-disco-f429zi-headers/7001/12?u=vit

Could you add `"disco_f429zi": "STM32F429I-Discovery",` to ` platformio\packages\framework-stm32cube\platformio\variants_remap.json`? It's missed for 1+ year :)

**Comment by puzrin** [comment]
Could you comment when this can be fixed?

**Comment by valeros** [comment]
Hi @puzrin ! Sorry for the late reply, the `stm32cube` package now includes the variant for `disco_f429zi` please run pio update to download the latest revision.
