### ISSUE TITLE
Add support for STM32L562 Discovery kit

### ISSUE THREAD

**Issue by Quincy-Zh** [platformio/platform-ststm32#432]
Product page: https://www.st.com/en/evaluation-tools/stm32l562e-dk.html

**Comment by fpistm** [comment]
FYI, L5 support will be added soon to the STM32 core.

**Comment by valeros** [comment]
Resolved in https://github.com/platformio/platform-ststm32/commit/746a07b5da187b5ee7e8db4218d174bfc53373c6
