### ISSUE TITLE
Custom HAL configuration support

### ISSUE THREAD

**Issue by daniel-starke** [platformio/platform-ststm32#437]
When using STM32CubeMX you set up the periphery and it generates for example a `stm32l4xx_hal_conf.h` out of this.
PlatformIO uses another approach by just including everything using the provided template header. See
https://github.com/platformio/platform-ststm32/blob/09c1cf74a98851358c950bdf74327b7385e1cd93/builder/frameworks/stm32cube.py#L142-L155
Please provide a way to set up a custom HAL configuration per project/environment to allow more custom designs. E.g. this could be an already existing `stm32l4xx_hal_conf.h` in the specific project which is used instead of the template file if available. Just always generate the file to ensure proper function with non-customized projects.

Some effort was already made in that direction [here](https://community.platformio.org/t/into-the-quest-for-a-cubemx-framework/8036) but I would prefer a solution by PlatformIO to keep the other parts of the build script up-to-date.

**Comment by valeros** [comment]
Thanks, resolved in https://github.com/platformio/platform-ststm32/commit/ec29fab5f4e75ad7664cefcfc723e3acc6e22592.
Now we won't generate a default configuration if the `build.stm32cube.custom_config_header` option is set to `yes`.
