### ISSUE TITLE
__dso_handle linker error for STM32F429I-Disc1

### ISSUE THREAD

**Issue by pwnorbitals** [platformio/platform-ststm32#440]
Linker error for default LibOpenCM3 project.
Fixed by adding -fno-use-cxa-atexit

**Comment by valeros** [comment]
Hi @pwnorbitals ! Thanks for reporting! How can I reproduce the issue?

**Comment by pwnorbitals** [comment]
I just tried to reproduce the issue and it doesn't happen. For reproduction, I use the miniblink example (https://github.com/libopencm3/libopencm3-examples/blob/master/examples/stm32/f4/stm32f429i-discovery/miniblink/miniblink.c) and a default-configured platformio project. We can probably close this issue, I will reopen if I can reproduce later on
