### ISSUE TITLE
RHF76-052 OpenOCD target

### ISSUE THREAD

**Issue by MMucka** [platformio/platform-ststm32#450]
In file boards\ **rhf76_052.json**  is problem with OpenOCD target file. 
After every platform update I have to change it manually in my system. 

There is:
"debug": {
    "jlink_device": "STM32L051C8",
    "openocd_target": "stm32l0**x**",
    "svd_path": "STM32L051x.svd"

should be:
"debug": {
    "jlink_device": "STM32L051C8",
    "openocd_target": "stm32l0",
    "svd_path": "STM32L051x.svd"

It is not possible to debug without this change. I don't have permission to create commit. Can somebody please fix it?
Thank you

**Comment by valeros** [comment]
Many thanks for pointing this out.
