### ISSUE TITLE
Arduino Portenta

### ISSUE THREAD

**Issue by JSCLadon** [platformio/platform-ststm32#457]
I would really appreciate if the Arduino Portenta would be added to the list of supported boards!

I wonder if I am the only one ;-)

Thanks a lot!

**Comment by MosiMiso** [comment]
Would also really appreciate it.
Thanks a lot in advance

**Comment by maxgerhardt** [comment]
Can you check https://github.com/platformio/platform-ststm32/pull/494?

**Comment by utkarshsethi** [comment]
There is already #494 open for this.

**Comment by valeros** [comment]
Resolved in https://github.com/platformio/platform-ststm32/pull/494, released in [12.1.0](https://github.com/platformio/platform-ststm32/releases/tag/v12.1.0)
