### ISSUE TITLE
Cannot select uploader when multiple JLinks are connected

### ISSUE THREAD

**Issue by angrypig7** [platformio/platform-ststm32#464]
Commit 76b76094b191582d31a9ef364a71fb4fa4bb6a65 disabled JLink GUI when uploading, which led to disabling the JLink selector popup screen when multiple uploaders are connected.
Therefore, it only uses the first JLink connected.

![image](https://user-images.githubusercontent.com/26675060/103460621-0ff4db80-4d5b-11eb-9c55-875c8bcc6954.png)

**Comment by valeros** [comment]
Hi @angrypig7 ! Indeed, the CLI mode is now default option. If you need to use a specific J-Link probe, please use the `-SelectEmuBySN` flag in the `upload_flags` feild, for example:
```
[env:black_f407ve]
platform = ststm32
framework = arduino
board = black_f407ve
upload_flags = 
    -SelectEmuBySN
    123456789
```
