### ISSUE TITLE
REQUEST: Update of framework-arduinoststm32

### ISSUE THREAD

**Issue by noisymime** [platformio/platform-ststm32#48]
Recently there has been a lot of pull requests brought into master on the base framework for stm32duino: https://github.com/rogerclarkmelbourne/Arduino_STM32

These have added significant functionality and additional compatibility with the arduino API. 

It looks like the last pull from this for package framework-arduinoststm32 2.0.0 was in Oct 2016.

Would it be possible to get a revised package version pulled from master on the above repo?

**Comment by ivankravets** [comment]
@ubis Could we update to the latest source code of stm32duino? Should we change build script?

**Comment by ubis** [comment]
I believe so, yes. I've looked at newer `boards.txt` and `platform.txt` to see changes. There wasn't any major changes at all.
So, it seems like no changes to stm32duino should be done.

**Comment by ivankravets** [comment]
@ubis Thank you very much! I've just updated a package. 

@noisymime please `pio update`.

**Comment by noisymime** [comment]
Tested and working. Huge thanks @ivankravets !
