### ISSUE TITLE
support for ST B-L4S5I-IOT01A STM32L4+ Discovery kit IoT node

### ISSUE THREAD

**Issue by eechev** [platformio/platform-ststm32#482]
Subj https://www.st.com/en/evaluation-tools/b-l4s5i-iot01a.html

**Comment by torntrousers** [comment]
I'd really like this too.

**Comment by valeros** [comment]
Resolved in https://github.com/platformio/platform-ststm32/commit/746a07b5da187b5ee7e8db4218d174bfc53373c6
