### ISSUE TITLE
KeyError("Invalid board option '%s'" % path)

### ISSUE THREAD

**Issue by zivf** [platformio/platform-ststm32#487]
PIO Core Call Error: "The current working directory /home/zivf/Documents/PlatformIO/Projects/stam1 will be used for the project.\n\nThe next files/directories have been created in /home/zivf/Documents/PlatformIO/Projects/stam1\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing stamdev_l412kb (platform: ststm32; board: stamdev_l412kb; framework: arduino)\n--------------------------------------------------------------------------------\nTool Manager: Installing framework-arduinoststm32 @ ~3.10500.190222\nTool Manager: framework-arduinoststm32 @ 3.10500.190327 has been installed!\nTool Manager: Installing platformio/tool-scons @ ~4.40001.0\nTool Manager: tool-scons @ 4.40001.0 has been installed!\nTool Manager: Removing tool-scons @ 3.30102.0\nTool Manager: tool-scons @ 3.30102.0 has been removed!\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/ststm32/stamdev_l412kb.html\nPLATFORM: ST STM32 (5.4.3) > STAMDEV L412KB\nHARDWARE: STM32L412KBU6 80MHz, 40KB RAM, 128KB Flash\nPACKAGES: \n - framework-arduinoststm32 3.10500.190327 (1.5.0) \n - toolchain-gccarmnoneeabi 1.70201.0 (7.2.1)\nWarning! Cannot find linker script for the current target!\n\nLDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf\nLDF Modes: Finder ~ chain, Compatibility ~ soft\nFound 7 compatible libraries\nScanning dependencies...\nNo dependencies\nBuilding in release mode\nKeyError: \"Invalid board option 'build.hwids'\":\n  File \"/home/zivf/.platformio/penv/lib/python3.6/site-packages/platformio/builder/main.py\", line 170:\n    env.SConscript(\"$BUILD_SCRIPT\")\n  File \"/home/zivf/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/SConscript.py\", line 598:\n    return _SConscript(self.fs, *files, **subst_kw)\n  File \"/home/zivf/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/SConscript.py\", line 287:\n    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\n  File \"/home/zivf/.platformio/platforms/ststm32/builder/main.py\", line 179:\n    _usbids = board.get(\"build.hwids\")\n  File \"/home/zivf/.platformio/penv/lib/python3.6/site-packages/platformio/platform/board.py\", line 59:\n    raise KeyError(\"Invalid board option '%s'\" % path)\n========================= [FAILED] Took 14.44 seconds ========================="

**Comment by valeros** [comment]
Hi @zivf ! Looks like your manifest for `stamdev_l412kb` doesn't have the `hwids` field, you check out this manifest as an example https://github.com/platformio/platform-ststm32/blob/develop/boards/econode_l082cz.json#L7
