### ISSUE TITLE
Arduino support for STM32F407

### ISSUE THREAD

**Issue by Split7fire** [platformio/platform-ststm32#49]
Please, add support for stm32duino on stm32f407vgt6. It is know to work well with Arduino IDE

**Comment by atrips** [comment]
I will be happy that too: stm32f407v* series. Thank you for the effort and the great project !

**Comment by volodink** [comment]
+1

**Comment by sczekajewski** [comment]
Just made a pull request with support of stm32f4 from stm32duino project. Check out the pull request https://github.com/platformio/platform-ststm32/pull/101 and see if it works for you.

**Comment by ivankravets** [comment]
Added, please use `board = genericSTM32F407VET6`
