### ISSUE TITLE
STM32CubeIDE [makefile:93: fail-specified-linker-script-missing]  Error: Cannot find the specified linker script. Check the linker settings in the build configuration.

### ISSUE THREAD

**Issue by muhammedtapis** [platformio/platform-ststm32#507]
After i create my project in STM32CubeMX i can not run the code it says : [makefile:93: fail-specified-linker-script-missing]  Error: Cannot find the specified linker script. Check the linker settings in the build configuration. 
How do i solve this problem i cant find the linker settings, thanks !!! @ivankravets

**Comment by valeros** [comment]
This repo has nothing to do with STM32CubeIDE, please forward your question here https://community.st.com/s/topic/0TO0X000000y2j7WAA/stm32cubeide
