### ISSUE TITLE
fix for nucleo_f413zh.json

### ISSUE THREAD

**Issue by jcw** [platformio/platform-ststm32#508]
Please update the `nucleo_f413zh.json` board file, it contains:

    "svd_path": "STM32F41x.svd"

This should be:

    "svd_path": "STM32F413.svd"

The "Z" version has 144 pins, and many more UARTs and SPIs than listed in `STM32F41x.svd`.

(I've started auto-generating more and more header info from the chip/board details from these files, and bumped into this)

**Comment by valeros** [comment]
Thanks, fixed.
