### ISSUE TITLE
STM32 Compilation error

### ISSUE THREAD

**Issue by JulioCesarMatias** [platformio/platform-ststm32#530]
Hi,

I'm having a compilation problem with the STM32F103, you updated the core and caused the Arduino.h extension to return *h(variant_PILL_F103Cx.h) error. I've tried the `pio update` and `pio upgrade --dev` commands, but it didn't work.PlatformIO Core `version 5.2.0a6`

Platformio.ini >> https://github.com/JCFLIGHT/JCFLIGHT/blob/master/platformio.ini

Error after compilation:

arm-none-eabi-g++: error: C:/Users/Julio: No such file or directory
arm-none-eabi-g++: error: Cesar/.platformio/packages/framework-arduinoststm32/variants/STM32F1xx/F103C8T_F103CB(T-U)/ldscript.ld: No such file or directory
arm-none-eabi-g++: error: Cesar/.platformio/packages/framework-arduinoststm32/variants/STM32F1xx/F103C8T_F103CB(T-U): No such file or directory
*** [.pio\build\JCFlightPascal\firmware.elf] Error 1

![Captura de tela 2021-06-03 230224](https://user-images.githubusercontent.com/25625982/120734771-d79b2a00-c4bf-11eb-82d5-942d0b7ecc55.png)

**Comment by valeros** [comment]
Hi @JulioCesarMatias ! Could you please try to update the platform package to the latest version? Just run `pio platform update ststm32` and try again.

**Comment by JulioCesarMatias** [comment]
didn't solve

![113473930-ec7e2180-946c-11eb-88c4-c07e8d872b13](https://user-images.githubusercontent.com/25625982/120834955-1a014d00-c53a-11eb-9396-0d292399c25a.png)

**Comment by JulioCesarMatias** [comment]
![Uploading Captura de tela 2021-06-04 133941.png…]()

**Comment by valeros** [comment]
Please run `pio platform show ststm32` in the IDE terminal and upload the output to https://pastebin.com/

**Comment by JulioCesarMatias** [comment]
> Please run `pio platform show ststm32` in the IDE terminal and upload the output to https://pastebin.com/

https://pastebin.com/hWHVDYe7

**Comment by valeros** [comment]
Thanks, also could you please clean the project, compile it in verbose mode and upload the log to https://pastebin.com/ as well:
![image](https://user-images.githubusercontent.com/886732/120838547-99117800-c570-11eb-9422-3e88c575801b.png)

**Comment by JulioCesarMatias** [comment]
> Obrigado, você também poderia limpar o projeto, compilá-lo em modo detalhado e enviar o log para https://pastebin.com/ também:
> ![imagem](https://user-images.githubusercontent.com/886732/120838547-99117800-c570-11eb-9422-3e88c575801b.png)

https://pastebin.com/eb79Wfuh

**Comment by valeros** [comment]
It seems that you didn't copy the entire log, I can only see few lines. You need to clean your project and only then compile it in verbose mode.

**Comment by JulioCesarMatias** [comment]
> It seems that you didn't copy the entire log, I can only see few lines. You need to clean your project and only then compile it in verbose mode.


I updated, I put the entire log

**Comment by valeros** [comment]
Strange, but I cannot reproduce the issue. Could you try to delete the `C:\Users\Julio Cesar\.platformio` folder and try again?

**Comment by JulioCesarMatias** [comment]
After I did the Verbose Build, the problem disappeared, now it compiles normally. This was a PlatformIO Bug, maybe it is not cleaning up what is needed for a new build. I as a programmer found it strange too, but @valeros thanks for your attention!
