### ISSUE TITLE
vccgnd_f407zg_mini

### ISSUE THREAD

**Issue by darkspr1te** [platformio/platform-ststm32#535]
in file 
[vccgnd_f407zg_mini.json](https://github.com/platformio/platform-ststm32/blob/develop/boards/vccgnd_f407zg_mini.json)
the openocd target is set to stm32f1x target cpu and not f4 target causing upload errors in openocd,
current line reads 
` "debug": {
    "jlink_device": "STM32F407ZG",
    "openocd_target": "stm32f1x",
    "svd_path": "STM32F407xx.svd"
  },
`
correct line should be
 `"debug": {
    "jlink_device": "STM32F407ZG",
    "openocd_target": "stm32f4x",
    "svd_path": "STM32F407xx.svd"
  },`

darkspr1te

**Comment by valeros** [comment]
Thanks, fixed.
