### ISSUE TITLE
Update Zephyr to 2.6.0

### ISSUE THREAD

**Issue by maxgerhardt** [platformio/platform-ststm32#541]
Per https://github.com/zephyrproject-rtos/zephyr/releases this is released now. Should also be done for all other platforms using Zephyr.

**Comment by valeros** [comment]
Updated in https://github.com/platformio/platform-ststm32/commit/08a8f2c3ade5356909a7574c6abea02cf3f4c3d2.

**Comment by zpm1066** [comment]
Thanks @valeros.
