### ISSUE TITLE
Support for  STM32F427VIT6

### ISSUE THREAD

**Issue by natyshemer** [platformio/platform-ststm32#548]
Hi, 
I was wondering if there is any plan to support the STM32F427VIT6 board?
Thank you
Naty

**Comment by valeros** [comment]
Hi @natyshemer ! You can use the `armstrap_eagle2048` board, it has the same MCU.

**Comment by natyshemer** [comment]
Hi , this is great. 
Do you know if there any plans to support the Arduino framework with this board?

**Comment by valeros** [comment]
I'd recommend you to ask in the Arduino repository.

**Comment by natyshemer** [comment]
Sorry but from what I understood the Arduino framework has been archived and is now only refers to Atmel boards. Did you mean this repo?
![image](https://user-images.githubusercontent.com/57321229/127158773-de28b5be-78d2-496a-9172-6c5f64aabbb7.png)

**Comment by valeros** [comment]
I meant this repo https://github.com/stm32duino/Arduino_Core_STM32
