### ISSUE TITLE
Missing lora-e5 device

### ISSUE THREAD

**Issue by vmaurice** [platformio/platform-ststm32#581]
Hello,

Starting with Zephyr version 2.7, they added the SeeedStudio lora-e5 board.

https://docs.zephyrproject.org/latest/boards/arm/lora_e5_dev_board/doc/lora_e5_dev_board.html
https://docs.zephyrproject.org/latest/releases/release-notes-2.7.html

Can you add it to PlatformIO ?

Thanks

**Comment by nobodywasishere** [comment]
I've started work on #596

**Comment by valeros** [comment]
Resolved in https://github.com/platformio/platform-ststm32/issues/596
