### ISSUE TITLE
PlatformIO doesn't follow the CMakeLists.txt instructions while compiling

### ISSUE THREAD

**Issue by prayassamriya** [platformio/platform-ststm32#584]
Hello,

I have a STM32 and Zephyr OS based project for which the requirement is that same code/repo I should be able to build using platform IO as well as west command using CLI. I am able to achieve it however I see that I need to make duplicate efforts everytime I make changes in the project structure/add the files/delete the files etc. to make the west build work, I add the target sources for the files I want to build. there are other files which are either not ready or not tested( or some samples/examples ). since these files shouldn't be part of the build process ( I cannot remove those from repo for various reasons ) I just don't add those into CMakeLists.txt. I also have some files which should be compiled only when a feature is enabled for that I use target_source_ifdef( CONFIG_MY_FEATURE App PRIVATE my_feature_file_name.c ). It all works and build great using west but when I try to build the same using platform IO it simply builds all the files it finds. I know that I can use platformio.ini to include/exclude the files and folders but that is what I don't want to do. its a duplicate efforts. not easy to maintain for multi target, multi years and multi developers project. I assume that this problem is known but still I have created an example project to replicate the same problem.
Please let me know I can I build same zephyr project using platformio and west with keeping the configuration just same using CMakeLists. in summary, I want to find the common approach and configuration for building my zephyr based project in both platformIO and West.
for more information related to example and the problem, refer main.c file in below zipped project.
[211123-184204-zephyr-blink.zip](https://github.com/platformio/platform-ststm32/files/7593053/211123-184204-zephyr-blink.zip)

**Comment by valeros** [comment]
Hi @prayassamriya ! In a nutshell, PlatformIO uses a different build system and consequently, different build workflow. The files specified in `target_sources` are used only for generating build configurations. The duplicate efforts are necessary steps if you want keep your project compatible with the usual Zephyr workflow.
