### ISSUE TITLE
SDBlockDevice and FATFileSystem not working

### ISSUE THREAD

**Issue by mcprakash** [platformio/platform-ststm32#59]
Hi 
 I am trying  to do a simple SPI read/write to an SD card using the following libraries

> SDBlockDevice.h
> FATFileSystem.h

 I am having trouble with the `-D PIO_FRAMEWORK_MBED_FILESYSTEM_PRESENT` flag. 

 The exact output message is attached in screenshot.
![screenshot from 2017-07-25 12-00-18](https://user-images.githubusercontent.com/8052668/28588893-db37751a-7130-11e7-99c8-9262ad991d93.png)

 However, if I go to the `mbed-os` github repository for `v5.50`, I am able to see the `FATFileSystem` library.

 Could you help me with this ? Thanks

Chandra

**Comment by mcprakash** [comment]
@ivankravets @valeros I tried a simple hello world program with the flag -D PIO_FRAMEWORK_MBED_FILESYSTEM_PRESENT and I get compile time error. PFA the attahced snapshot for further reference. It will be great if you can help me out. 

![screenshot from 2017-08-01 16-06-33](https://user-images.githubusercontent.com/8052668/28850863-d668b7ee-76d3-11e7-936a-f5df9359db03.png)

**Comment by DL6AKU** [comment]
I am having the same problem here.

```
.platformio/packages/framework-mbed/mbed.h:50:10: fatal error: filesystem/mbed_filesystem.h: No such file or directory
#include "filesystem/mbed_filesystem.h"
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/nucleo_l476rg/FrameworkMbedCore/platform/FileSystemHandle.o] Error 1
```

**Comment by mcprakash** [comment]
Hi DL6AKU, 
 I switched to mbed command line tool and it works without any issues. I think there is a problem with ST-NUCLEO devices and SD FILE System libraries when used together with platformio in mbed environment.
 Hope this helps. 
Best
Chandra
