### ISSUE TITLE
Flashing problem Arduino_STM32 DFU devices

### ISSUE THREAD

**Issue by kwetter** [platformio/platform-ststm32#60]
I have a new chinese board with a STM32F103CBT6; 1 reset button, 1 user button.

I like to program it over its inbuilt USB with the Arduino_STM32 framework.
I'm working on OSX 10.11 with dfu-utils installed over homebrew.

my init file:
[env:genericSTM32F103CB]
platform = ststm32
board = genericSTM32F103CB
framework = arduino
upload_protocol = dfu

A simple Blink Sketch compiles but i get an error: "no upload_port".
In concole: "dfu-util -l" i can see 2 DFU devices for the board (FLASH and RAM).
The bootloader on the board is blinking the LED fast, holding both buttons sets the LED low.

I tried several reset timings with the reset button and/or user button. No success as the DFU wont get recognized by platformio...

Maybe another bootloader is necessary?

On a side note: I tried with it's little brother board STM32F103C8T6, with only 1 reset button and BOOT0/BOOT1 options.
Here i could successfully flash the bootloader 2.0 with a USB-TTL converter. Flashing over USB does not succeed with same error as above (similar init file). "dfu-util -l" does not show me any devices though. Thorough resetting tactics did not succeed.

After a few days of trials I might just give up and program the boards with my USB-TTL adapter.

Maybe someone could present me the proper workflow (flashing bootloaders, installations for platformio/dfu-utils/STM32frameworks, init files,..) as I might have done something wrong there...

Thanks!

**Comment by kwetter** [comment]
Seems i got it working for the Maple Mini Clone (STM32F103CBT6) with following init file:
[env:maple_mini_origin]
platform = ststm32
board = maple_mini_origin
framework = arduino
upload_protocol = dfu

problem persists though with the BluePill (STM32F103C8T6) and this init file:
[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = arduino
upload_protocol = dfu

any hints?

**Comment by kwetter** [comment]
Got it working, so for what it's worth for others:

The Blue Pill Board (STM32F103C8T6) works for upload via USB with dfu-util installed on OSX with following platformio.ini:

platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_port = anything
upload_protocol = dfu

i had to define upload_port (doesn't matter what...). I still have to reset the board manually right before uploading.

maybe there's a better solution, but I think I'm satisfied for the moment :)

**Comment by ubis** [comment]
To able to flash board within dfu, you need to have stm32bootloader installed. Choose the correct one from [here](https://github.com/rogerclarkmelbourne/STM32duino-bootloader/tree/master/STM32F1/binaries). Usually PC13 is port to which LED is connected, so `generic_boot20_pc13.bin` should work in this case.

To flash it, you need usb-ttl converter(ft232rl for example) and set both BOOT's to BOOT1: 0; BOOT0: 1. More info [here](http://www.stm32duino.com/viewtopic.php?t=413).

However, most of these boards contain wrong usb pull-up resistor on D+. More info about it [here](http://wiki.stm32duino.com/index.php?title=Blue_Pill). I had some issues that sometimes it couldn't reset after flash, so i've changed pull-up resistor to 1k5. 

After flashing, set BOOT0 back to 0 and use usb from now on. When creating new project, you can use BluePill board, and set `upload_protocol = dfu`

I'm not sure if you really need to set `upload_port` on unix based systems, but in case it won't automatically find it - you might need it to add it. Thats pretty much it.

**Comment by kwetter** [comment]
thanks ubis for the tip about the wrong pull-up resistor. I might fix it with the known work-around.
