### ISSUE TITLE
How to use STM32F030C6T6 ?

### ISSUE THREAD

**Issue by Witawat** [platformio/platform-ststm32#623]
How to use STM32F030C6T6 support arduino ?

i can't find document in https://docs.platformio.org/en/latest/boards/index.html

but i see in list 

STM32F030C6, STM32F030C8, STM32F030F4, STM32F030K6, STM32F030R8,STM32F030.svd

**Comment by maxgerhardt** [comment]
FYI a test project for a STM32F030C6 was created at https://community.platformio.org/t/how-to-config-stm32f030c6t6-support-arduino-framework/27609/21?u=maxgerhardt. 

Still, PlatformIO is missing the genericSTM32F0xxx definitions.

**Comment by maxgerhardt** [comment]
I think the issue should stay open until new board definitions are added by the developers.
