### ISSUE TITLE
genericSTM32F103Vx Clock Frequency

### ISSUE THREAD

**Issue by nopnop2002** [platformio/platform-ststm32#628]
### Configuration

**Operating system**:
Linux (ubuntu)

**PlatformIO Version** (`platformio --version`):
PlatformIO Core, version 5.2.5

### Description of problem

I built with this variant.

genericSTM32F103VB/VC/VD/VE

The clock frequency is set to 64MHz instead of 72MHz.

Is this the correct behavior?

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = genericSTM32F103VE

[env:genericSTM32F103VB]
platform = ststm32
board = genericSTM32F103VB
framework = arduino

[env:genericSTM32F103VC]
platform = ststm32
board = genericSTM32F103VC
framework = arduino

[env:genericSTM32F103VD]
platform = ststm32
board = genericSTM32F103VD
framework = arduino

[env:genericSTM32F103VE]
platform = ststm32
board = genericSTM32F103VE
framework = arduino


```

**Source file to reproduce issue:**
```cpp
#include <Arduino.h>
HardwareSerial Serial1(USART1);
//HardwareSerial Serial2(USART2);
HardwareSerial Serial3(USART3);

#define BAUDRATE 115200

void setup() {
  Serial3.begin(BAUDRATE); Serial3.println("serial 3"); // PB10/PB11
  Serial2.begin(BAUDRATE); Serial2.println("serial 2"); // PA2/PA3
  Serial1.begin(BAUDRATE); Serial1.println("serial 1"); // PA9/PA10
}

void loop() {
  Serial3.println("serial 3");
  Serial3.println(F_CPU);
  Serial2.println("serial 2");
  Serial2.println(F_CPU);
  Serial1.println("serial 1");
  Serial1.println(F_CPU);
  Serial.println("serial (same as 2)");
  Serial.println("*****");
  delay(1000);
}
```

![STM32F103Vx](https://user-images.githubusercontent.com/6020549/170221732-78068697-0fbb-4fb3-a5c5-507be53a95b6.jpg)

**Comment by maxgerhardt** [comment]
>genericSTM32F103VB/VC/VD/VE
>
>The clock frequency is set to 64MHz instead of 72MHz.

Board maps to variant

https://github.com/platformio/platform-ststm32/blob/9ce784b031f5fb0dfac6dd5cda33ef4ab58191db/boards/genericSTM32F103VB.json#L19

And https://github.com/stm32duino/Arduino_Core_STM32/tree/main/variants/STM32F1xx/F103V8(H-T)_F103VB(H-I-T) only has one clock code in [generic_clock.c](https://github.com/stm32duino/Arduino_Core_STM32/blob/main/variants/STM32F1xx/F103V8(H-T)_F103VB(H-I-T)/generic_clock.c). If the USB communication is enabled, it clocks the CPU by HSI / 2 * 12, with HSI = 8MHz, that is 48 Mhz, else, by HSI / 2 * 16 = 64MHz.

If you have a high-speed crystal (HSE) on the board, you can achieve the full frequency, which is what PlatformIO always lists. It does not account for default clock init code of different frameworks. To do this, you have to place a function in your firmware, e.g. in the `src/main.cpp` file, with

```cpp
extern "C" void SystemClock_Config(void)
{
  // clock init code here
}
```
and that inner code can e.g. be generated with STM32CubeMX's clock configurator tool.

**Comment by nopnop2002** [comment]
I did another test with a bluepill board


# blackpill_f103c8             STM32F103C8T6   72MHz        64KB      20KB      BlackPill F103C8


```
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = bluepill_f103c8

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
```

F_CPU show 72000000


# genericSTM32F103C8           STM32F103C8T6   72MHz        64KB      20KB      STM32F103C8 (20k RAM. 64k Flash)


```
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = genericSTM32F103CB

[env:genericSTM32F103CB]
platform = ststm32
board = genericSTM32F103CB
framework = arduino
```



F_CPU show 64000000

**Comment by maxgerhardt** [comment]
`board = bluepill_f103c8` shows F_CPU = 72000000 because it [its clock code configures it to do so](https://github.com/stm32duino/Arduino_Core_STM32/blob/main/variants/STM32F1xx/F103C8T_F103CB(T-U)/variant_PILL_F103Cx.cpp#L103-L108), HSE (=8MHz) / 1 * 9 = 72 MHz.

`board = genericSTM32F103C8` shows  F_CPU = 64000000 because it [its clock code configures it to do so](https://github.com/stm32duino/Arduino_Core_STM32/blob/main/variants/STM32F1xx/F103C8T_F103CB(T-U)/generic_clock.c#L68-L72), HSI (=8MHz) / 2 * 16 = 64 MHz.

**Comment by nopnop2002** [comment]
@maxgerhardt 

Thank you for the commentary.

I would like to keep this issues open for others.

**Comment by nopnop2002** [comment]
@maxgerhardt 


Don't you think 72Mhz on this list should be changed?

![STM32F103Vx](https://user-images.githubusercontent.com/6020549/170221732-78068697-0fbb-4fb3-a5c5-507be53a95b6.jpg)

**Comment by nopnop2002** [comment]
@maxgerhardt 

I got it.

**Comment by valeros** [comment]
The board manifest contains maximum chip frequency that has nothing to do with specific particular settings.
