### ISSUE TITLE
Project Initialisation fails for board: mts_mdot_f411re

### ISSUE THREAD

**Issue by nigelb** [platformio/platform-ststm32#63]
On the page with all of the boards ([http://platformio.org/boards](http://platformio.org/boards)), when one searches for mdot, two boards show up:

- MultiTech mDot - `mts_mdot_f405rg`
- MultiTech mDot F411 - `mts_mdot_f411re`

Initialising a project with `mts_mdot_f405rg` works fine:

	'C:\Users\Billy Bob\.python\pio\Scripts\pio.exe' init --board mts_mdot_f405rg --ide clion

	The current working directory C:\Users\Billy Bob\Documents\projects\ucontroller\Feral will be used for project.
	You can specify another project directory via
	`platformio init -d %PATH_TO_THE_PROJECT_DIR%` command.

	The next files/directories have been created in C:\Users\Billy Bob\Documents\projects\ucontroller\Feral
	platformio.ini - Project Configuration File
	src - Put your source files here
	lib - Put here project specific (private) libraries

	Project has been successfully initialized!
	Useful commands:
	`platformio run` - process/build project from the current directory
	`platformio run --target upload` or `platformio run -t upload` - upload firmware to embedded board
	`platformio run --target clean` - clean project (remove compiled files)
	`platformio run --help` - additional information

However initialising with `mts_mdot_f411re` fails:

	'C:\Users\Billy Bob\.python\pio\Scripts\pio.exe' init --board mts_mdot_f411re --ide clion

	The current working directory C:\Users\Billy Bob\Documents\projects\ucontroller\Feral will be used for project.
	You can specify another project directory via
	`platformio init -d %PATH_TO_THE_PROJECT_DIR%` command.

	The next files/directories have been created in C:\Users\Billy Bob\Documents\projects\ucontroller\Feral
	platformio.ini - Project Configuration File
	src - Put your source files here
	lib - Put here project specific (private) libraries
	Cannot find the configuration file for your board! Please read instructions here C:\Users\Billy Bob\.platformio\packages\framework-mbed\platformio\README.txt
	============================================== [ERROR] Took 0.66 seconds ==============================================

Following the instructions in the README.txt file did not resolve the issue.

**Comment by ivankravets** [comment]
Fixed. Thanks!
