### ISSUE TITLE
mbed-filesystem compile error

### ISSUE THREAD

**Issue by eeyurdakul** [platformio/platform-ststm32#65]
macOS 10.12.6
PlatformIO 3.5.0a8

compile error when   **#include "SDFileSystem.h"**   is added to main.cpp.
**build_flags = -D PIO_FRAMEWORK_MBED_FILESYSTEM_PRESENT** is added to **platformio.ini** but problem still not solved.

Compile error is as follows:
**/Users/eeyurdakul/.platformio/packages/framework-mbed/mbed.h:51:40: fatal error: filesystem/mbed_filesystem.h: No such file or directory**

**Comment by valeros** [comment]
Hi, @eeyurdakul! There is no such header in the framework. You can try [this one](https://developer.mbed.org/handbook/SDFileSystem) but only with `mbed 2`.

**Comment by eeyurdakul** [comment]
How can I try it with mbed 2. Do I downgrade the firmware?

**Comment by valeros** [comment]
`mbed 2` is enabled by default, therefore you can simply add the SDFileSystem library to your project.

**Comment by eeyurdakul** [comment]
Here is the error when I add "#include "SDFileSystem.h" to the project.

/.platformio/packages/framework-mbed/mbed.h:51:40: fatal error: filesystem/mbed_filesystem.h: No such file or directory

**Comment by eeyurdakul** [comment]
Sorry, I forgot to add the library. Now it works...Thanks
