### ISSUE TITLE
Wrong define generated by PlatformIO when using a generic UxN-variant

### ISSUE THREAD

**Issue by microtronics** [platformio/platform-ststm32#651]
### Description of problem

When executing "pio run" it should automatically define -DARDUINO_GENERIC_G071GBUXN as this is the define required by the variant_generic-files. However, it only defines -DARDUINO_GENERIC_G071GBUX and thus one has to manually add the correct define. Looks like the filename is truncated one letter too early.

#### Steps to Reproduce

1. Use the platformio.ini
2. Add the board json to project/boards and linker script
3. Try to compile an empty example

### Actual Results

Fails due to not finding some parts of the variant_generic code.

### Expected Results

Succesful build by automaticall generating the correct define.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:generic_g071gbuxn]
platform = ststm32
board = generic_G071GBUXN
framework = arduino
```

**Source file to reproduce issue:**
```generic_g071gbuxn.json
{
  "build": {
    "core": "stm32",
    "cpu": "cortex-m0plus",
    "extra_flags": "-DSTM32G0xx -DSTM32G071xx",
    "f_cpu": "64000000L",
    "framework_extra_flags": {
      "arduino": "-D__CORTEX_SC=0"
    },
    "mcu": "stm32g071gbuxn",
    "product_line": "STM32G071xx",
    "variant": "STM32G0xx/G071G(8-B)UxN_G081GBUxN"
  },
  "debug": {
    "default_tools": [
      "stlink"
    ],
    "jlink_device": "STM32G071GB",
    "onboard_tools": [
      "stlink"
    ],
    "openocd_target": "stm32g0x",
    "svd_path": "STM32G071.svd"
  },
  "frameworks": [
    "arduino",
    "cmsis",
    "libopencm3",
    "stm32cube",
    "zephyr"
  ],
  "name": "Generic G071GBUxN",
  "upload": {
    "maximum_ram_size": 36864,
    "maximum_size": 131072,
    "protocol": "stlink",
    "protocols": [
      "stlink",
      "jlink",
      "cmsis-dap",
      "blackmagic",
      "mbed"
    ]
  },
  "url": "https://www.st.com/en/microcontrollers-microprocessors/stm32g071gb.html",
  "vendor": "ST"
}
```
[GenericG071GBUXNtest.zip](https://github.com/platformio/platform-ststm32/files/9783822/GenericG071GBUXNtest.zip)

**Comment by valeros** [comment]
Hi @microtronics, you're already using a custom board manifest just add `-DARDUINO_GENERIC_G071GBUXN` to the `extra_flags` field.
