### ISSUE TITLE
Feature Request: Include STM32duino 2.3.0

### ISSUE THREAD

**Issue by JeroenIoT** [platformio/platform-ststm32#659]
Hello,

I am happily using platformIO for development of STM32 software based on stm32duino. 

* The ststm32 platform release today is at release 15.4.1.
* The latest STM32duino version in platformio is at v2.2.0 (included in STSTM32 platform in release 15.3.0)
* The latest STM32duino release is 2.3.0 (June 2022).
-- https://github.com/stm32duino/Arduino_Core_STM32/releases/tag/2.3.0

Could this latest stm32duino version (2.3.0) be added to the ststm32 platform?

Thanks a lot

**Comment by Miceuz** [comment]
This workaround works quite well, but it would be nice to have the latest framework-arduinoststm32 in repository.
```
platform_packages =
   framework-arduinoststm32@https://github.com/stm32duino/Arduino_Core_STM32.git#2.3.0
```

**Comment by JeroenIoT** [comment]
FYI -> In the meantime the stm32duino 2.4.0 is released (21-dec-2022)
