### ISSUE TITLE
STM32CUBEMX Direct Import to Platformio

### ISSUE THREAD

**Issue by eeyurdakul** [platformio/platform-ststm32#66]
It would be nice if we can use stm32cubemx files in stm32 platform.

**Comment by ddildine11** [comment]
I agree it would greatly simplify adding new boards

**Comment by ivankravets** [comment]
Do you mean this?

* https://github.com/platformio/platform-ststm32/tree/develop/examples/stm32cube-hal-blink
* https://github.com/platformio/platform-ststm32/tree/develop/examples/stm32cube-ll-blink

**Comment by ivankravets** [comment]
Please reopen if you still need help
