### ISSUE TITLE
can't upload (stlink, raspi 32-bit)

### ISSUE THREAD

**Issue by jcw** [platformio/platform-ststm32#660]
What kind of issue is this?

- [X] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

------------------------------------------------------------------

### Configuration

**Operating system**: Linux piodev 5.15.76-v7+ platformio/platformio-core#1597 SMP Fri Nov 4 12:13:17 GMT 2022 armv7l GNU/Linux

**PlatformIO Version** (`platformio --version`): 6.1.6a3

### Description of problem
This looks like a regression. I've started using my RasPi build farm again for PIO. I get this error:

```
Processing f413 (board: nucleo_f413zh; platform: ststm32; framework: cmsis)
-------------------------------------------------------------------------------------
Tool Manager: Installing platformio/tool-dfuutil @ ~1.11.0
Error: Could not find the package with 'platformio/tool-dfuutil @ ~1.11.0' requirements for your system 'linux_armv7l'
```

#### Steps to Reproduce

1. build & upload any STM32 project w/ latest PIO on RasPi, I suppose ...

### Expected Results
When I remove a few lines from `platforms/ststm32/platform.json`, things work as expected again. I.e. proper openocd upload.

The lines removed were:

```
"tool-dfuutil": { ... }
```

It's not clear why there is this dependency on `dfu-util` (which does not provide an ARM build on SourceForge, btw).

### Additional info
Note that this build setup is still using 32-bit Linux.
I can supply more info if needed, of course.

**Comment by ivankravets** [comment]
Could you navigate to https://sourceforge.net/p/dfu-util/dfu-util/ci/v0.11/tree/ , click on "Download Snapshot" , and compile it on armv7l target? Next step. please pack binaries with zip or tar.gz (if there are symbolic links), and share an archive somewhere. We will publish the package to the registry.

Thanks!

**Comment by ivankravets** [comment]
Could you align the archive to [this](https://dl.registry.platformio.org/download/platformio/tool/tool-dfuutil/1.11.0/tool-dfuutil-linux_aarch64-1.11.0.tar.gz) structure? Where could we get `libusb.so`?

**Comment by ivankravets** [comment]
Thanks! Uploaded! https://registry.platformio.org/tools/platformio/tool-dfuutil/compatibility

Could you remove this package from `~/.platformio/packages` folder and try to flash a board?

**Comment by ivankravets** [comment]
Great! Thank you so much for the help with binaries! 🙏🤗
