### ISSUE TITLE
Add support for Leafony STM32

### ISSUE THREAD

**Issue by masa6372** [platformio/platform-ststm32#663]
Hi

We are currently developing our original STM32 board Leafony STM32 (https://docs.leafony.com/en/docs/leaf/processor/ap03/) and want to use Platform IO.
However we couldn't find the way to create our original board file for this board.
Is there any documentation to publish our board in PlatformIO?

Thanks!

Document: https://docs.leafony.com/en/docs/leaf/processor/ap03/
Schematics: https://github.com/Leafony/HW-Design-Files/blob/master/AP03_STM32_MCU/AP03_STM32_MCU_Schematic.pdf
Where can be purchased: https://shop.leafony.com/en/collections/products/products/basic-kit-2

**Comment by maxgerhardt** [comment]
If your board is a NUCLEO L452RE equivalent and shall be primarily via `serial`, duplicate https://github.com/platformio/platform-ststm32/blob/develop/boards/nucleo_l452re.json, adapt name and vendor, remove the on-board debug tools section, set protocol to serial and add that as the first element in the protocols array too, done.
