### ISSUE TITLE
Support NUCLEO-C031C6 board, which based on stm32c0 is missing

### ISSUE THREAD

**Issue by martiinezz** [platformio/platform-ststm32#687]
Hi,

There is new AVR killer released: https://www.st.com/en/evaluation-tools/nucleo-c031c6.html but I don't see support for such board here.
Looks like Arduino_Core_STM32 already added support in 2.5-dev 

Thanks

**Comment by fpistm** [comment]
> Looks like Arduino_Core_STM32 already added support in 2.5-dev

Yes it is supported in the main branch but not yet released. Next release planned before end of march.

**Comment by martiinezz** [comment]
OK so waiting for release or I can test it beforehand?
