### ISSUE TITLE
Incorrect clock setting for all STM32F1xx devices

### ISSUE THREAD

**Issue by jcw** [platformio/platform-ststm32#698]
What kind of issue is this?

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

### Configuration
```
platform = ststm32
framework = cmsis
board = bluepill_f103c8   (for example ...)
```

**Operating system**: MacOS 13.3.1

**PlatformIO Version** (`platformio --version`): 6.1.7

### Description of problem
When starting up, the `SystemCoreClock` variable is set to 16000000 iso 8000000.
This is done in `framework-cmsis-stm32f1/Source/Templates/system_stm32f1xx.c`, line 123.
The 16 MHz value is correct for STM32F4xx, but for STM32F1xx HSI is always 8 MHz, as documented in `RM0008.pdf`.

It took me a while to track this down, I didn't understand why all my baudrate calculations were off by a factor of 2, unless the clock was explicitly changed to say 72 MHz using the PLL (at which point `SystemCoreClock` also gets modified).

**Comment by valeros** [comment]
Hi @jcw ! I'm not sure how we can fix it. As you mentioned, the value of the `SystemCoreClock` variable is set in the official package distributed by ST and we have no control over that source files. If this is a bug, shouldn't it be fixed https://github.com/STMicroelectronics/cmsis_device_f1/blob/master/Source/Templates/system_stm32f1xx.c#L141 here in the first place?
