### ISSUE TITLE
Miss Arduino Giga R1 WiFi and Nicla Voice and Nicla Vision all cores

### ISSUE THREAD

**Issue by port513** [platformio/platform-ststm32#704]
### Configuration

**Operating system**: Windows 10 x64

**PlatformIO Version** (`platformio --version`):
PlatformIO Core, version 6.1.7

### Description of problem
Miss out board support for Nicla Voice and Arduino Giga R1 WiFi

**Comment by valeros** [comment]
Duplicate #702
