### ISSUE TITLE
Update for Zephyr 3.4.0 ?

### ISSUE THREAD

**Issue by mtnrbq** [platformio/platform-ststm32#706]
Hi,

Is an official platformio update to support Zephyr 3.4.0 in progress ?

Alternatively, any guidance on manually updating ?

I've tried this  [community post](https://community.platformio.org/t/how-to-set-platformio-to-use-the-latest-branch-of-zephyr/16702) but ran into issues and was not sure if it should still work.

**Comment by valeros** [comment]
Updated in [v17.0.0](https://github.com/platformio/platform-ststm32/releases/tag/v17.0.0)
