### ISSUE TITLE
Update to Arduino Core for STM32 2.6.0

### ISSUE THREAD

**Issue by vshymanskyy** [platformio/platform-ststm32#718]
I'm interested in LORA_E5_MINI (STM32WLE5JC) board support which was added in:
https://github.com/stm32duino/Arduino_Core_STM32/commit/aed76aae10d274b4ee86c9c43dc3ed23fead5565

@valeros this would also affect #581 #624 #596

**Comment by RudolphRiedel** [comment]
That would also add STM32H5 support and I have a Nucleo-H503RB that I would like to see working with PlatformIO.

**Comment by sstaub** [comment]
Nucleo H563ZI board is also missing.

**Comment by vshymanskyy** [comment]
Thank you @valeros !
Timing is perfect

**Comment by vshymanskyy** [comment]
It's still unclear on how to actually select this board in Platformio...
It's STM32WLE5JC, In Arduino IDE it's under `stm32:LoRa`, than you need to select `Tools -> Board Part Number -> LoRa-E5 mini`

**Comment by vshymanskyy** [comment]
I was able to use LoRa-E5 mini:
```ini
[env:lora-e5]
platform = ststm32@17.0.0
board = lora_e5_mini
framework = arduino
debug_tool = stlink
upload_protocol = stlink
```

**Comment by ypearson-bdai** [comment]
Any updates to support nucleo_h563zi?

I'm getting `: Unknown board ID 'nucleo_h563zi'`
