### ISSUE TITLE
Cannot parse c_cpp_properties.json for stm32h723zg on vscode

### ISSUE THREAD

**Issue by asukiaaa** [platformio/platform-ststm32#732]
VSCode cpp plugin cannot parse the following path on .vscode/c_cpp_properties.json with using ststm32@17.0.0.

```
"/home/asuki/.platformio/packages/framework-arduinoststm32/variants/STM32H7xx/H723Z\(E-G\)T_H730ZBT_H733ZGT",
```

```ini
;; platformio.ini
[env:nucleo_h723zg]
platform = ststm32@17.0.0
board = nucleo_h723zg
framework = arduino
```

It's no problem with using ststm32@16.1.0.

My environment:
OS: Ubuntu22.04
VSCode: 1.82.2
PlatformIO: 6.1.11

**Comment by valeros** [comment]
Hi @asukiaaa, thanks for reporting, should be fixed in the latest Arduino package, please update your packages via `pio pkg update -g -p ststm32` in the IDE terminal.
