### ISSUE TITLE
Couldn't find any ST-Link/V2 devices

### ISSUE THREAD

**Issue by me21** [platformio/platform-ststm32#74]
When I try to flash Blue Pill STM32F103C8 board from Platformio, I get the error mentioned in issue title. Tool output is:

```
st-util 1.3.1
2017-10-31T12:24:26 WARN src\usb.c: Couldn't find any ST-Link/V2 devices
```

The STM32 ST-LINK utility from manufacturer works just fine.

Please update tool-stlink to the latest version. Currently that's 1.4.0 in upstream. Maybe the bug there is fixed. At least there was similar issue https://github.com/texane/stlink/issues/486 which is now closed.

Or maybe consider switching to ST-LINK_CLI utility from tool-stm32duino. It sees my ST-Link device.

**Comment by ivankravets** [comment]
Could you re-test with?

platformio.ini
```
[env:...]
platform = https://github.com/platformio/platform-ststm32.git
board =...
```

Does it work now?

**Comment by me21** [comment]
Ah, I've sorted it out myself already. I'm sorry for not reporting :(
The cause was that I've inserted ST-LINK device into USB 3.0 port. It didn't work with USB 3.0. When I inserted it into USB 2.0 port, everything worked like a charm.

**Comment by me21** [comment]
Ah, I've sorted it out myself already. I'm sorry for not reporting :(
See https://github.com/texane/stlink/issues/651. In short, my USB 3.0 controller driver was buggy and I needed to update it.
