### ISSUE TITLE
Zephyr RTOS boilerplate.cmake deprecated

### ISSUE THREAD

**Issue by StoneBam** [platformio/platform-ststm32#752]
Hi!

I'm getting the following error when configuring "Zephyr RTOS" for my "ST NUCLEO H753ZI":
```
C:/Users/<name_replaced>/.platformio/packages/framework-zephyr/.cache
-- Zephyr version: 3.4.0 (C:/Users/<name_replaced>/.platformio/packages/framework-zephyr), build: zephyr-v30400
-- Board: nucleo_h753zi
-- Configuring incomplete, errors occurred!

CMake Warning at C:/Users/<name_replaced>/.platformio/packages/framework-zephyr/cmake/app/boilerplate.cmake:20 (message):
 Loading of Zephyr boilerplate.cmake directly is deprecated, please use
 'find_package(Zephyr)'
Call Stack (most recent call first):
 CMakeLists.txt:2 (include)
 
 
Loading Zephyr default modules (Zephyr base).
CMake Error at C:/Users/<name_replaced>/.platformio/packages/framework-zephyr/cmake/modules/configuration_files.cmake:76 (message):
 No prj.conf file was found in the
 C:/Users/<name_replaced>/git/stm32_first_steps/stm32_second/STM32_second/zephyr
 folder, please read the Zephyr documentation on application development.
Call Stack (most recent call first):
 C:/Users/<name_replaced>/.platformio/packages/framework-zephyr/cmake/modules/zephyr_default.cmake:115 (include)
 C:/Users/<name_replaced>/.platformio/packages/framework-zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
 C:/Users/<name_replaced>/.platformio/packages/framework-zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
 C:/Users/<name_replaced>/.platformio/packages/framework-zephyr/cmake/app/boilerplate.cmake:25 (find_package)
 CMakeLists.txt:2 (include)
 
 
========================== [FAILED] Took 3.21 seconds ==========================
```
It says the `boilerplate.cmake` is deprecated but I don't find documentation on this error to fix the problem myself.
Simply replacing the mentioned line in the partial set up project with the suggested `find_package(Zephyr)` doesn't work of course.

Here the content of the `CMakeLists.txt`:
```
cmake_minimum_required(VERSION 3.13.1)
include($ENV{ZEPHYR_BASE}/cmake/app/boilerplate.cmake NO_POLICY_SCOPE)
project(STM32_second)

FILE(GLOB app_sources ../src/*.c*)
target_sources(app PRIVATE ${app_sources})
```

And here the content of the `boilerplate.cmake`:
```cmake
# SPDX-License-Identifier: Apache-2.0

######################################
# The use of this file is deprecated #
######################################

# To build a Zephyr application it must start with one of those lines:
#
# find_package(Zephyr)
# find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
#
# The `REQUIRED HINTS $ENV{ZEPHYR_BASE}` variant is required for any application
# inside the Zephyr repository.
#
# Loading of this file directly is deprecated and only kept for backward compatibility.

if(NOT DEFINED Zephyr_DIR)
  # When `find_package(Zephyr)` is used then `Zephyr_DIR` is defined, else
  # old style inclusion is used. Warning is only printed in first invocation.
  message(WARNING "Loading of Zephyr boilerplate.cmake directly is deprecated, "
          "please use 'find_package(Zephyr)'"
  )
endif()

find_package(Zephyr REQUIRED PATHS ${CMAKE_CURRENT_LIST_DIR}/../.. NO_DEFAULT_PATH)
```

I tried to follow the [Platformio docs](https://docs.platformio.org/en/latest/frameworks/zephyr.html) but it didn't help (or I did it wrong) and looked for similar issues but didn't find any for this Problem. I couldn't figure out what the contents of `prj.conf` have to be either, the file wasn't generated.
From [this Issue](https://github.com/platformio/platformio-core/issues/1613#issuecomment-554683964) I'm aware that supporting Zephyr was a difficult endeavor. Is Zephyr still supported or is it moving to fast with to many changes to keep up to?

Can someone help me, or point me to resources I may have missed?
Is the setting up Zephyr Projects via the "PlatformIO IDE for VS Code" recommended at all?

Thank you in advance!

## EDIT
I think I solved the issue, sry for wasting everyones time. May it help others neither the less
1. Navigate to the folder with the failed build.
2. Replace the boilerplate part in the `CMakeLists.txt` in the `zephyr` directory with this line `find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})` from [here](https://docs.zephyrproject.org/latest/build/zephyr_cmake_package.html#zephyr-cmake-package)
3. place an empty `prj.conf` in the `zephyr` directory
4. Try again setting up the project with platform io in the same directory as before

Not yet sure if it will build and run as well but at least no more error messages.

**Comment by valeros** [comment]
@mbUSC Zephyr is supported so it's no longer relevant.
