### ISSUE TITLE
Support Arduino Framework for ST Nucleo H753ZI

### ISSUE THREAD

**Issue by derdiedasoli** [platformio/platform-ststm32#785]
Currently, the Arduino framework for this board is apparently unsupported.

The issue is: the STM32Duino Framework core _supports_ the board, using it through the Arduino IDE works! However, when creating a platformio project and declaring the framework as `arduino`, I receive an error that the board is in fact unsupported for the framework.

Please add support for the `arduino` framework for this board, or alternatively, please point me in the right direction to overwrite this error.

**Comment by valeros** [comment]
Resolved in https://github.com/platformio/platform-ststm32/commit/53e776666fa4b16eda508689160adc5d0fb091a1
