### ISSUE TITLE
Corrupted config for the genericSTM32U585CIU6  board

### ISSUE THREAD

**Issue by Zer0-bit** [platformio/platform-ststm32#788]
Hi - as the title suggests on adding this custom config with a plain blink example the runtime throws a hard fault after flashing via platformi, flashing via arduino ide the exact same example wiht the same board selected in the settings everything works.

Here's the json  definition of the custom board i added, both platformio and arduino ide are using the same **variants** folder mainly the **variants\STM32U5xx\U575C(G-I)(T-U)_U585CI(T-U)** 
```json
{
    "build": {
      "core": "stm32",
      "cpu": "cortex-m33",
      "mcu": "stm32u585ciu6",
      "board": "GENERIC_U585CIUX",
      "extra_flags": "-DSTM32U5 -DSTM32U5xx -DSTM32U585xx",
      "f_cpu": "160000000L",
      "product_line": "STM32U585xx",
      "variant": "STM32U5xx/U575C(G-I)(T-U)_U585CI(T-U)"
    },
    "debug": {
      "jlink_device": "stm32u585ciu6",
      "openocd_target": "stm32u5x",
      "svd_path": "STM32u585xx.svd"
    },
    "frameworks": [
      "arduino",
      "cmsis",
      "stm32cube",
      "libopencm3",
      "zephyr"
    ],
    "name": "GENERIC_U585CIUX",
    "upload": {
      "maximum_ram_size": 804864,
      "maximum_size": 2097152,
      "protocol": "stlink",
      "protocols": [
        "jlink",
        "cmsis-dap",
        "stlink",
        "blackmagic",
        "serial",
        "dfu"
      ]
    },
    "url": "https://www.st.com/en/microcontrollers-microprocessors/stm32u585ci.html",
    "vendor": "ST"
  }
  ```
  
Either way i have checked everything i could and could not figure out why the blink example works under arduino ide and not under platformio.

Here is the blink example i used:
```cpp
#define LED_PIN PC13

void setup()
{
  // initialize LED digital pin as an output.
  pinMode(LED_PIN, OUTPUT);
}

void loop()
{
  // turn the LED on (HIGH is the voltage level)
  digitalWrite(LED_PIN, HIGH);
  // wait for a second
  delay(1000);
  // turn the LED off by making the voltage LOW
  digitalWrite(LED_PIN, LOW);
   // wait for a second
  delay(1000);
}
```

Also here is the platformio task definition:
```ini
[env:stm-32]
framework = arduino
platform = ststm32@17.4.0
board = genericSTM32U585CIU6
upload_protocol = stlink
monitor_speed = 115200
```

Here's a STM32 CubeProgreammer Fault Analyzer screnshot, this only occurs when flashing via platformio be it directly via upload or pushing the bin file via CubeProgrammer.
![image](https://github.com/user-attachments/assets/46c1733e-dd5e-4a0a-b503-feafd791ed18)

Any help would be greately appreciated, thank you.

**Comment by valeros** [comment]
Hi @Zer0-bit, the first thing that catches the eye is discrepancy in the size of RAM. You specified `804864` while in the Arduino repo this value is set to `786432`. 

Please keep in mind there is no official support for the STM32U5 series in this development platform, hence there is no any guarantee it will work as expected.
