### ISSUE TITLE
Update to ArduinoCore-mbed 4.1.5

### ISSUE THREAD

**Issue by papakpmartin** [platformio/platform-ststm32#789]
[ArduinoCore-mbed 4.1.5](https://github.com/arduino/ArduinoCore-mbed/releases/tag/4.1.5). It would be great to get this out soon.

This resolves some  nasty DHCP and Ethernet issues.

Thanks! :)

Side question: Is there a way that I could point to this new code before this update gets all the way through this repo?

**Comment by valeros** [comment]
Added in [v17.5.0](https://github.com/platformio/platform-ststm32/releases/tag/)
