### ISSUE TITLE
stm32l4 board  bw_swan_r5 framework arduiono library for USBHost or usbkeyboard support??

### ISSUE THREAD

**Issue by pedrogmnzmr** [platformio/platform-ststm32#807]
Hi, I am starting a project with the bw_swan_r5 board that has an STM32L4R5ZIY6 MCU. I want to use the Arduino framework but I can't find any compatible library to use USB as a host. I already have a configured Adafruit TFT display with its corresponding library, and I would like to connect a USB keyboard to input data and display it on the screen.

**Comment by valeros** [comment]
Hi @pedrogmnzmr , this repository is not the right place to ask project-specific questions, see https://github.com/stm32duino/Arduino_Core_STM32/issues/687
