### ISSUE TITLE
Nucleo F439ZI supported since STM32duino release 2.8.0, still not in Platformio release 17.6.0?

### ISSUE THREAD

**Issue by pmantoine** [platformio/platform-ststm32#814]
Reading your releases, you state that since release 17.5.0 of PlatformIO's stsm32 core you have been up to date with STM32duino's Arduino core release 2.8.1

I worked with the STM32duino Arduino core team to include Nucleo F439ZI support into releases since 2.8.0, but Arduino framework support is still not listed in PlatformIO's stsm32 nucleo_f439zi.json file in boards.

Is something amiss?

[nucleo_f439zi.json](https://github.com/user-attachments/files/17711857/nucleo_f439zi.json)

**Comment by valeros** [comment]
You've already asked this question in https://github.com/platformio/platform-ststm32/issues/802, haven't you? The Arduino framework for this board will be available in the next release of this platform. In the meantime, you can test it out using the upstream version of the platform:
```ini
[env:nucleo_f439zi]
platform = https://github.com/platformio/platform-ststm32.git
framework = arduino
board = nucleo_f439zi
```
