### ISSUE TITLE
STM32duino Opta PlatformIO Build Error: Missing 'stm32_def.h' File

### ISSUE THREAD

**Issue by osamahnini** [platformio/platform-ststm32#815]
Describe the bug When attempting to build the project using PlatformIO with the Arduino framework for the Opta board, the compilation fails with a fatal error indicating that the stm32_def.h file is missing.

To Reproduce

Set up a PlatformIO project configured for the Opta board with the following platform and framework in platformio.ini:
ini
```
[env:opta]
platform = https://github.com/platformio/platform-ststm32.git
board = opta
framework = arduino
```
Include the following libraries in your platformio.ini:
ini

```
lib_deps =
  STM32duino RTC@1.5.0
  ArduinoModbus@1.0.9
  ArduinoRS485@1.1.0
  ArduinoJson@7.2.1
  WiFi@1.2.7
  NTPClient@3.2.1+sha.61684d4
  ArduinoECCX08@1.3.8
  ArduinoBearSSL@1.7.4
  ArduinoMqttClient@0.1.8
  Arduino_ConnectionHandler@1.0.0
  ArduinoHttpClient@0.6.1
  SSLClient@1.3.2
  Arduino Cloud Provider Examples@1.2.1
  Wifi
```

Attempt to build the project by running the build command in PlatformIO.
Observe the compilation error related to the missing stm32_def.h file.
Expected behavior The project should compile successfully without any missing file errors, resulting in a valid firmware binary for the Opta board.

OS: Windows 10
PlatformIO Version: 5.2.1 (example version; please specify your actual version)
STM32 core version: Using PlatformIO's platform-ststm32 at version 17.6.0+sha.9f7c0d8
Library versions: As listed in lib_deps
Upload method: SWD
Hardware (please complete the following information):

Board Name: Opta
Hardware Revision: Not specified
Extra hardware used if any:
STM32H747XIH6
WiFi module
RTC module
Additional context During the build process, the compiler cannot locate the stm32_def.h file, resulting in a fatal error. Below is the relevant portion of the build log:

```
In file included from .pio\libdeps\opta\STM32duino RTC\src\rtc.c:37:0:
.pio\libdeps\opta\STM32duino RTC\src\rtc.h:42:10: fatal error: stm32_def.h: No such file or directory

*******************************************************************
* Looking for stm32_def.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:stm32_def.h"
* Web  > https://registry.platformio.org/search?q=header:stm32_def.h
*
*******************************************************************

 #include "stm32_def.h"
          ^~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\opta\libdae\STM32duino RTC\rtc.c.o] Error 1
```
Summary of Issue:

Missing Header File: The build fails because the stm32_def.h file is not found. This suggests that a directed dependency is missing or not properly included in the project.
Suggested Actions:

Verify Library Dependencies: Ensure that all necessary libraries, especially those that provide the stm32_def.h file, are correctly installed and included in the project.
Search for the Missing File: Use the PlatformIO library registry to search for and include the missing stm32_def.h file.
CLI: platformio lib search "header:stm32_def.h"
Web: [PlatformIO Library Registry](https://registry.platformio.org/search?q=header:stm32_def.h)
Check Library Compatibility: Confirm that the versions of the libraries used are compatible with the platform-ststm32 and the Opta board.
Update or Install Missing Libraries: If the stm32_def.h file is part of a specific library, add it to your lib_deps in platformio.ini.
Additional Resources:

[PlatformIO Library Registry](https://registry.platformio.org/)
[stm32duino GitHub Repository](https://github.com/stm32duino/Arduino_Core_STM32)
[stm32duino Forum](https://stm32duino.com/)

**Comment by valeros** [comment]
Hi @osamahnini, the `STM32duino RTC` library is not compatible with the Opta board because this board uses a completely different Arduino core based on the mbed framework.
