### ISSUE TITLE
STM32Cube framework is listed twice for the BluePill

### ISSUE THREAD

**Issue by jcw** [platformio/platform-ststm32#95]
As the title says. Not sure what's going on here.

Update: this happens in more places, e.g. F103xx generic.

Update #2: it gets weirder, I now see it listed 3x. I've been creating a few new projects to try things out.

**Comment by ivankravets** [comment]
Could you provide a screenshot?

**Comment by ubis** [comment]
I think @jcw meant this: [L41](https://github.com/platformio/platform-ststm32/blob/develop/boards/bluepill_f103c8.json#L41) and [L44](https://github.com/platformio/platform-ststm32/blob/develop/boards/bluepill_f103c8.json#L44).

**Comment by jcw** [comment]
Ah, sorry, yes:

<img width="326" alt="screen shot 2018-03-15 at 21 12 57" src="https://user-images.githubusercontent.com/148955/37488706-c724045e-2895-11e8-95dc-bdf2899dda92.png">

**Comment by ivankravets** [comment]
Thanks, guys! I fixed.

@jcw Which IDE do you use? With which theme?

**Comment by jcw** [comment]
Atom w/ Atom Light on Mac. Thx for fixing. If I run into other little quirks, I'll submit more little issues :)

**Comment by ivankravets** [comment]
Great! :)

Happy coding with PlatformIO!
